import { hookMetadataLine } from "../core/hook-registries.js";

/**
 * Portable hook script template (.mjs, Node only, zero dependencies). The
 * metadata comment on the first line is what `sync` re-reads to regenerate
 * the registrations — the matcher travels with the script.
 */
export function renderHookScript(input: {
  event: string;
  matcher: string | undefined;
}): string {
  return [
    hookMetadataLine(input.event, input.matcher),
    "//",
    "// Portable hook script generated by agentsdir. One script, every harness:",
    "// Claude Code, Codex and Cursor all invoke it the same way, with no",
    "// dependency beyond Node itself.",
    "//",
    "// Protocol (common to the three harnesses):",
    `//   stdin   one JSON payload describing the ${input.event} event.`,
    "//   stdout  empty to let the event proceed silently, or a single JSON",
    '//           object (starting with "{") to send a decision or context back.',
    "//   exit 0  success — the harness continues.",
    "//   exit 2  block — stderr explains the refusal to the agent.",
    "//   other   non-blocking error, surfaced to the user.",
    "",
    "const payload = await readPayload();",
    "",
    `// TODO: implement the ${input.event} decision. To block, for example:`,
    '//   console.error("blocked: state the reason here");',
    "//   process.exit(2);",
    "void payload;",
    "",
    "process.exit(0);",
    "",
    "async function readPayload() {",
    '  let raw = "";',
    "  for await (const chunk of process.stdin) {",
    "    raw += chunk;",
    "  }",
    '  return raw.trim() === "" ? {} : JSON.parse(raw);',
    "}",
    "",
  ].join("\n");
}
