import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { runCheck } from "../../commands/check.js";
import { runInit } from "../../commands/init.js";
import { runSync } from "../../commands/sync.js";
import { EXIT_CODES } from "../../exit-codes.js";
import { initAnswers, makeTempDir } from "../../test-support/index.js";

/**
 * A write interrupted mid-file must stay repairable. It did not: a truncated
 * copy lost the generated header, read as a foreign file, and `sync` refused
 * the very repair `check` was demanding — a dead end whose only way out was
 * deleting the file by hand. The manifest fingerprint is the evidence of
 * ownership: a path it records was written by a previous run.
 */
describe("core - an interrupted write stays repairable", () => {
  it("Given a truncated projection, When sync runs, Then it repairs it and check goes green", async () => {
    const dir = await makeTempDir("interrupted");
    await runInit(dir, initAnswers(), { dryRun: false });
    const bridge = join(dir, "CLAUDE.md");
    await writeFile(bridge, "@AGE", "utf8"); // killed mid-write

    expect((await runCheck(dir)).exitCode).toBe(EXIT_CODES.driftOrInvariant);
    expect((await runSync(dir, { dryRun: false })).exitCode).toBe(
      EXIT_CODES.ok,
    );
    expect(await readFile(bridge, "utf8")).toContain("@AGENTS.md");
    expect((await runCheck(dir)).exitCode).toBe(EXIT_CODES.ok);
  });

  it("Given a CLAUDE.md the user wrote, When init runs, Then it refuses and the content survives", async () => {
    const dir = await makeTempDir("interrupted-user");
    const bridge = join(dir, "CLAUDE.md");
    await writeFile(bridge, "# Mine\n\nPrecious content.\n", "utf8");

    const failure = await runInit(dir, initAnswers(), {
      dryRun: false,
    }).catch((error: unknown) => error);

    expect(failure).toBeInstanceOf(Error);
    expect((failure as Error).message).toMatch(
      /was not generated by agentsdir/,
    );
    expect(await readFile(bridge, "utf8")).toContain("Precious content.");
  });
});
