import type { PackContent, PackFile } from "./index.js";

/**
 * Pack `creator`: the assisted-creation meta-skills — the heart of the
 * product (docs/creation-assistee.md). Tier 1 (the CLI generators) guarantees
 * the structure; these meta-skills guide the harness agent to produce the
 * CONTENT, through the six-step protocol: inventory → targeted interview →
 * routing → draft + critique → generate then write → mandatory `check`.
 * Four artifact creators plus `$setup-context` (the AGENTS.md entry point).
 * Written in English (product content, not design documentation).
 */
export function creatorPack(): PackContent {
  const files: PackFile[] = [];
  for (const skill of [
    createSkillMeta(),
    createHookMeta(),
    createRuleMeta(),
    createAgentMeta(),
    setupContextMeta(),
  ]) {
    files.push(
      {
        path: `.agents/skills/${skill.name}/SKILL.md`,
        content: skill.skillMd,
      },
      {
        path: `.agents/skills/${skill.name}/references/rubrique.md`,
        content: skill.rubric,
      },
      {
        path: `.agents/skills/${skill.name}/references/interview.md`,
        content: skill.interview,
      },
    );
  }
  return {
    name: "creator",
    files,
    skills: [
      "create-skill",
      "create-hook",
      "create-rule",
      "create-agent",
      "setup-context",
    ],
    rules: [],
    keepExisting: [],
  };
}

/** The official filter question — quoted verbatim in every meta-skill body. */
export const FILTER_QUESTION =
  "if this line is deleted, will the agent make a mistake?";

interface MetaSkill {
  name: string;
  skillMd: string;
  rubric: string;
  interview: string;
}

function frontmatter(fields: {
  name: string;
  description: string;
  displayName: string;
  shortDescription: string;
  color: string;
  icon: string;
  defaultPrompt: string;
}): string[] {
  return [
    "---",
    `name: ${fields.name}`,
    `description: "${fields.description}"`,
    "disable-model-invocation: true",
    `display-name: "${fields.displayName}"`,
    `short-description: "${fields.shortDescription}"`,
    `color: "${fields.color}"`,
    `icon: ${fields.icon}`,
    `default-prompt: "${fields.defaultPrompt}"`,
    "implicit: false",
    "---",
    "",
  ];
}

function createSkillMeta(): MetaSkill {
  const skillMd = [
    ...frontmatter({
      name: "create-skill",
      description:
        "Creates a complete, high-quality skill through inventory, targeted interview, draft, critique and mechanical validation. Use when the user asks to create, design or improve a skill, a slash command or a reusable agent workflow.",
      displayName: "Create Skill",
      shortDescription: "Assisted creation of a skill that passes check",
      color: "#7C3AED",
      icon: "sparkles",
      defaultPrompt:
        "Use $create-skill to create a new skill by guided interview.",
    }),
    "# Create Skill",
    "",
    "The CLI guarantees the structure (`agentsdir add skill`); this meta-skill",
    "guides the content. Nothing is delivered before `agentsdir check` passes.",
    "Follow the six steps in order — never skip the critique or the check.",
    "",
    "## 1. Inventory before creating",
    "",
    "- Read AGENTS.md, the rules index and every folder under `.agents/skills/`",
    "  before writing anything. Never write over existing material: if a",
    "  similar skill exists, propose improving it instead of duplicating it.",
    "- Note the project's terminology and commands — the new skill must reuse",
    "  them, not invent parallel vocabulary.",
    "",
    "## 2. Targeted interview",
    "",
    "- Ask ONLY what the code cannot answer. The question bank is in",
    "  references/interview.md — pick the discriminating questions, dig into",
    "  the hard points the user did not anticipate, skip the obvious.",
    "",
    "## 3. Routing",
    "",
    "- Qualify the need before creating anything: advisory knowledge belongs in",
    "  a rule (use $create-rule); an on-demand workflow is a skill (continue);",
    "  something guaranteed to run every time is a hook (use $create-hook);",
    "  bulky, isolable work is a sub-agent (use $create-agent). A misrouted",
    "  need produces a dead artifact — reroute instead of pressing on.",
    "",
    "## 4. Draft, then critique",
    "",
    "- Draft the body from the answers, then criticize it line by line with",
    '  the filter question: "if this line is deleted, will the agent make a mistake?"',
    "  Remove every line whose deletion would cause no mistake.",
    "- Run the trigger test: collect at least 3 user phrases that MUST trigger",
    "  the skill and at least 2 near-miss phrases that must NOT. Rework the",
    "  description until it separates them: third person, what + when, the",
    '  user\'s own keywords — never "Helps with…".',
    "- Check the draft against every criterion of references/rubrique.md.",
    "",
    "## 5. Generate, then write",
    "",
    "- Run `agentsdir add skill <name> --json` to create a valid skeleton and",
    "  its Codex projections, then replace the template body with the drafted",
    "  content and set the frontmatter fields from the interview (description,",
    "  display-name, short-description, color, icon, default-prompt).",
    "- Run `agentsdir sync` so the Codex artifacts match the final frontmatter.",
    "- Show the result to the user before finalizing (the generators accept",
    "  `--dry-run` when the user wants to preview the skeleton first).",
    "",
    "## 6. Mechanical validation — mandatory",
    "",
    "- Run `agentsdir check`. Any deviation goes back to step 4: never conclude",
    "  with a failing check, and paste the passing check output when done.",
    "",
  ].join("\n");
  const rubric = [
    "# Skill quality rubric",
    "",
    "Criteria marked ▣ are enforced mechanically by `agentsdir check`; the",
    "others belong to the critique pass (step 4).",
    "",
    "## ▣ Mechanical — check fails on these",
    "",
    "- ▣ `name`: 1-64 characters of a-z, 0-9 and -, equal to the folder name.",
    "- ▣ Body between 12 and 500 significant lines; bulky knowledge moves to a",
    "  references folder (progressive disclosure, ONE level of indirection).",
    "- ▣ Complete extended frontmatter: display-name, short-description of 25",
    "  to 64 characters, color #RRGGBB, icon from the embedded set,",
    "  default-prompt containing the exact `$<name>` token.",
    "- ▣ `disable-model-invocation: true` on any skill that can write;",
    "  `implicit` reserved for read-only skills (invocation parity).",
    "- ▣ Every references, scripts or steps path mentioned in the body exists",
    "  on disk — a dead pointer is a lying skill.",
    "- ▣ Codex artifacts byte-identical to the frontmatter render (run `sync`).",
    "",
    "## Critique pass",
    "",
    "- Description in third person: what + when + the user's own trigger",
    '  keywords — never "Helps with…".',
    "- Trigger test recorded: at least 3 phrases that must trigger, at least 2",
    "  near-misses that must not.",
    "- Explicit degrees of freedom: a fragile sequence becomes an executable",
    "  script, not prose; several valid approaches become instructions.",
    "- One default plus one escape hatch — never a menu of options.",
    "- Constant terminology; no perishable information (versions, dates, URLs).",
    '- Every line passes the filter question: "if this line is deleted, will the agent make a mistake?"',
    "",
  ].join("\n");
  const interview = [
    "# Interview bank — skill",
    "",
    "Ask only what the code cannot answer. The five discriminating questions,",
    "each derived from a sourced anti-pattern:",
    "",
    "1. Give at least 3 phrases that MUST trigger this skill, and at least 2",
    "   near-miss phrases that must NOT. (Feeds the description and the",
    "   trigger test.)",
    "2. Is the output objective (one verifiable right answer) or subjective",
    "   (judgment)? (Objective outputs deserve scripts and checks; subjective",
    "   ones deserve criteria.)",
    "3. Which fragile sequence should be frozen into an executable script",
    "   rather than described in prose?",
    "4. What did you repeat to the agent the last 3 times you did this by",
    "   hand? (That repetition IS the skill body.)",
    "5. Which knowledge is bulky but rarely needed? (It goes to a references",
    "   folder, loaded on demand — one level of indirection only.)",
    "",
    "Follow up when an answer stays vague: ask for the exact command, the",
    "exact file, the exact failure — never accept a generality the code",
    "could contradict.",
    "",
  ].join("\n");
  return { name: "create-skill", skillMd, rubric, interview };
}

function createHookMeta(): MetaSkill {
  const skillMd = [
    ...frontmatter({
      name: "create-hook",
      description:
        "Creates a portable lifecycle hook registered on every enabled harness, with the right event and an explicit failure policy. Use when the user wants something to happen automatically on agent events — block, guard, log or notify.",
      displayName: "Create Hook",
      shortDescription: "Assisted creation of a multi-harness lifecycle hook",
      color: "#B45309",
      icon: "zap",
      defaultPrompt:
        "Use $create-hook to create a portable hook by guided interview.",
    }),
    "# Create Hook",
    "",
    "One portable Node script, registered on Claude Code, Codex and Cursor by",
    "`agentsdir add hook`. This meta-skill guides the decisions the generator",
    "cannot make: the event, the failure policy, and whether a hook is even",
    "the right tool. Follow the six steps in order.",
    "",
    "## 1. Inventory before creating",
    "",
    "- Read the existing scripts in `.agents/hooks/` and the registrations in",
    "  .claude/settings.json, .codex/hooks.json and .cursor/hooks.json — never",
    "  duplicate an existing hook; extend or replace it consciously.",
    "",
    "## 2. Targeted interview — routing questions first",
    "",
    "- The bank is in references/interview.md. Open with the routing question:",
    "  PREVENT or REACT?",
    "  - Prevent (cancel the action): a blocking event — PreToolUse,",
    "    UserPromptSubmit or Stop — and the script blocks with exit 2 (the",
    "    hook protocol, distinct from the CLI exit codes).",
    "  - React (observe, log, notify): PostToolUse and kin — they can cancel",
    "    nothing; never promise prevention on a react event.",
    "- Ask fail-open or fail-closed: when the script itself crashes, should",
    "  the action proceed (open) or be blocked (closed)? Write the answer as",
    "  a comment in the script — it is a policy, not an accident.",
    "",
    "## 3. Routing — a hook is NOT a security boundary",
    "",
    "- If the need is a hard security ban (secrets, destructive commands that",
    "  must NEVER run), do NOT create the hook. Stop and point the user to the",
    "  harness permission settings (deny rules), which enforce bans even when",
    "  a hook is skipped, times out or crashes. A hook may assist a policy; it",
    "  must never be the only thing standing between the agent and the damage.",
    "- Advisory guidance belongs in a rule (use $create-rule); an on-demand",
    "  workflow is a skill (use $create-skill).",
    "",
    "## 4. Draft, then critique",
    "",
    "- Draft the script logic, then criticize every line with the filter",
    '  question: "if this line is deleted, will the agent make a mistake?" —',
    "  a hook line that changes nothing is latency for free.",
    "- Check the draft against references/rubrique.md: Stop hooks carry the",
    "  stop_hook_active guard; the timeout matches the real work; a manual",
    "  test command is provided.",
    "",
    "## 5. Generate, then write",
    "",
    "- Run `agentsdir add hook <Event> --name <slug> [--matcher <tool>]` to",
    "  create the portable script and its three registrations, then implement",
    "  the TODO section of the generated script with the drafted logic.",
    "- Test it by hand from the repo root:",
    "  `echo '{}' | node .agents/hooks/<file>` — verify both the pass and the",
    "  block paths before concluding.",
    "",
    "## 6. Mechanical validation — mandatory",
    "",
    "- Run `agentsdir check`, then `agentsdir sync --dry-run` to prove the",
    "  registrations are in step. Any deviation goes back to step 4.",
    "",
  ].join("\n");
  const rubric = [
    "# Hook quality rubric",
    "",
    "Criteria marked ▣ are enforced mechanically by `agentsdir check` or by",
    "the generator; the others belong to the critique pass (step 4).",
    "",
    "## ▣ Mechanical",
    "",
    "- ▣ Portable Node script, no dependency, reading one JSON payload on",
    "  stdin; stdout empty or a single JSON object starting with `{`.",
    "- ▣ Registered identically on every enabled harness by the generator",
    "  (`node .agents/hooks/<file>` everywhere); regenerated by `sync`.",
    "- ▣ Event known to the matrix (unknown events are refused with exit 2).",
    "",
    "## Critique pass",
    "",
    "- Event coherent with the intent: prevent → blocking event (PreToolUse,",
    "  UserPromptSubmit, Stop) + exit 2; react → PostToolUse and kin, which",
    "  cancel nothing.",
    "- Fail-open or fail-closed chosen explicitly at the interview and",
    "  documented as a comment in the script.",
    "- A hook is NOT a security boundary: a hard ban lives in the harness",
    "  permissions — refuse to create a hook for it.",
    "- Stop hooks check stop_hook_active before acting (loop guard).",
    "- Timeout adapted to the real work; long work is async, never blocking.",
    "- A manual test is provided: `echo '<json>' | node .agents/hooks/<file>`.",
    "",
  ].join("\n");
  const interview = [
    "# Interview bank — hook",
    "",
    "Ask only what the code cannot answer. The five discriminating questions:",
    "",
    "1. Prevent or react? (Prevent → blocking event + exit 2; react →",
    "   PostToolUse and kin, which cancel nothing.)",
    "2. When the script itself fails, should the action pass (fail-open) or",
    "   be blocked (fail-closed)? Document the choice in the script.",
    "3. Is this a hard security ban? (Then it is NOT a hook: point to the",
    "   harness permission settings and stop.)",
    "4. Which tools or commands exactly should trigger it? (Feeds the",
    "   matcher; remember Cursor uses its own tool vocabulary.)",
    "5. How long does the work take at worst, and must the agent wait for it?",
    "   (Feeds the timeout and the blocking/async choice.)",
    "",
    "Follow up with the concrete payload: ask for one real example of the",
    "event (the command, the file, the prompt) and design against it.",
    "",
  ].join("\n");
  return { name: "create-hook", skillMd, rubric, interview };
}

function createRuleMeta(): MetaSkill {
  const skillMd = [
    ...frontmatter({
      name: "create-rule",
      description:
        "Creates a working rule anchored in an observed failure, at the house template, indexed in AGENTS.md. Use when the user wants the agent to always follow a project convention or to stop repeating an observed mistake.",
      displayName: "Create Rule",
      shortDescription: "Assisted creation of a rule that earns its place",
      color: "#1F4E8C",
      icon: "clipboard-list",
      defaultPrompt:
        "Use $create-rule to create a working rule by guided interview.",
    }),
    "# Create Rule",
    "",
    "A rule the agents actually follow starts from a failure someone actually",
    "observed. This meta-skill guides the content; `agentsdir add rule`",
    "guarantees the template and the index entry. Six steps, in order.",
    "",
    "## 1. Inventory before creating",
    "",
    "- Read the rules index in AGENTS.md and every file in `.agents/rules/`.",
    "  If the topic is already covered, improve the existing rule instead of",
    "  adding a competing one — two rules on one topic diverge within a week.",
    "",
    "## 2. Targeted interview",
    "",
    "- The bank is in references/interview.md. The anchor question comes",
    "  first: which OBSERVED failure justifies this rule? No observed failure,",
    "  no rule — a hypothetical fear produces noise the agent learns to skip.",
    "",
    "## 3. Routing",
    "",
    "- Mechanically verifiable behavior (formatting, lint, forbidden calls)",
    "  belongs to a linter, the CI or a hook (use $create-hook) — never send",
    "  an agent to do a linter's job.",
    "- An on-demand workflow is a skill (use $create-skill); bulky isolable",
    "  work is a sub-agent (use $create-agent). Advisory knowledge that must",
    "  be read in context — that is a rule: continue.",
    "",
    "## 4. Draft, then critique",
    "",
    "- Draft at the house template: H1, a first line stating WHEN to read the",
    "  rule, imperative tone (ALWAYS, NEVER), a real GOOD/BAD pair taken from",
    "  the observed failure, a reference table when useful.",
    "- Criticize every line with the filter",
    '  question: "if this line is deleted, will the agent make a mistake?"',
    "  Check the draft against references/rubrique.md.",
    "",
    "## 5. Generate, then write",
    "",
    '- Run `agentsdir add rule <name> [--paths "<glob>"]` — scope the rule to',
    "  files when it only concerns some — then replace the template body with",
    "  the drafted content, keeping the when-to-read line under the H1 (the",
    "  rules index of AGENTS.md is derived from it by `sync`).",
    "",
    "## 6. Mechanical validation — mandatory",
    "",
    "- Run `agentsdir check` (index in step, no dead reference). Any deviation",
    "  goes back to step 4.",
    "",
  ].join("\n");
  const rubric = [
    "# Rule quality rubric",
    "",
    "Criteria marked ▣ are enforced mechanically by `agentsdir check`; the",
    "others belong to the critique pass (step 4).",
    "",
    "## ▣ Mechanical",
    "",
    "- ▣ One line in the rules index of AGENTS.md (managed block), derived",
    "  from the when-to-read sentence under the H1 — regenerated by `sync`.",
    "- ▣ No normative reference to a file that does not exist: a dead anchor",
    "  makes the rule lie.",
    "",
    "## Critique pass",
    "",
    "- Anchored in an OBSERVED failure or a real divergence of the project —",
    "  never a hypothetical fear.",
    "- House template: H1, when-to-read line, imperative tone (ALWAYS, NEVER),",
    "  a GOOD/BAD pair taken from the real failure, tables when useful.",
    "- `paths:` frontmatter when the rule only concerns some files.",
    "- Nothing that a linter, the CI or a hook already enforces mechanically.",
    '- Every line passes the filter question: "if this line is deleted, will the agent make a mistake?"',
    "",
  ].join("\n");
  const interview = [
    "# Interview bank — rule",
    "",
    "Ask only what the code cannot answer. The five discriminating questions:",
    "",
    "1. Which observed failure justifies this rule? (No observed failure, no",
    "   rule.)",
    "2. Is it scoped to specific files? (Feeds the `paths:` frontmatter.)",
    "3. Could it be verified mechanically? (Then it belongs to a linter, the",
    "   CI or a hook — not to a rule.)",
    "4. When must an agent read it? (Feeds the when-to-read line under the",
    "   H1, and through it the rules index.)",
    "5. Give the real GOOD and BAD example from the failure — not an invented",
    "   one.",
    "",
    "Follow up until the failure is concrete: which file, which commit, what",
    "broke, what should have happened instead.",
    "",
  ].join("\n");
  return { name: "create-rule", skillMd, rubric, interview };
}

function createAgentMeta(): MetaSkill {
  const skillMd = [
    ...frontmatter({
      name: "create-agent",
      description:
        "Creates a focused sub-agent with a single responsibility, minimal tools, a motivated model and a required output format. Use when the user wants to delegate a bulky or specialized task to a separate agent that starts fresh.",
      displayName: "Create Agent",
      shortDescription: "Assisted creation of a focused sub-agent",
      color: "#0F766E",
      icon: "bot",
      defaultPrompt:
        "Use $create-agent to create a focused sub-agent by guided interview.",
    }),
    "# Create Agent",
    "",
    "A sub-agent starts fresh: it sees none of the parent conversation, and",
    "the parent only receives its final report. This meta-skill guides the",
    "content; `agentsdir add agent` guarantees the frontmatter Claude Code",
    "requires. Six steps, in order.",
    "",
    "## 1. Inventory before creating",
    "",
    "- Read `.agents/agents/` first: an overlapping agent is improved, never",
    "  duplicated. Keep the cumulated descriptions short — they share one",
    "  context budget in the parent.",
    "",
    "## 2. Targeted interview",
    "",
    "- The bank is in references/interview.md. The anchor question: which",
    "  SINGLE task, and how does the agent know it is finished?",
    "",
    "## 3. Routing",
    "",
    "- A sub-agent earns its place when the work is bulky or specialized AND",
    "  isolable. Advisory knowledge is a rule ($create-rule); an on-demand",
    "  workflow the main agent runs itself is a skill ($create-skill);",
    "  something guaranteed on every event is a hook ($create-hook).",
    "",
    "## 4. Draft, then critique",
    "",
    "- Draft the system prompt: single mission, the REQUIRED output format",
    "  (the parent receives only the report), and the boundaries. The prompt",
    "  must never assume access to the parent conversation.",
    "- Choose minimal tools (a reviewer has no Write or Edit) and a motivated",
    "  model: mechanical volume → a fast model; deep reasoning → a strong",
    "  one; otherwise inherit.",
    '- Third-person description stating WHEN to delegate; add "use',
    '  proactively" only when spontaneous delegation is wanted.',
    "- Criticize every line with the filter",
    '  question: "if this line is deleted, will the agent make a mistake?"',
    "  Check against references/rubrique.md.",
    "",
    "## 5. Generate, then write",
    "",
    "- Run `agentsdir add agent <name> [--model <model>]`, then replace the",
    "  template prompt with the drafted mission, output format and",
    "  boundaries, and set the description from the interview.",
    "",
    "## 6. Mechanical validation — mandatory",
    "",
    "- Run `agentsdir check`. Any deviation goes back to step 4.",
    "",
  ].join("\n");
  const rubric = [
    "# Sub-agent quality rubric",
    "",
    "Criteria marked ▣ are enforced mechanically; the others belong to the",
    "critique pass (step 4).",
    "",
    "## ▣ Mechanical",
    "",
    "- ▣ Frontmatter `name` (lowercase-with-dashes, equal to the file name)",
    "  and non-empty `description` — a file without them is ignored SILENTLY",
    "  by Claude Code, the sneakiest failure of the format.",
    "",
    "## Critique pass",
    "",
    "- One single responsibility, with an explicit definition of done.",
    "- Required output format in the body: the parent receives only the final",
    "  report, nothing else survives the sub-agent.",
    "- Minimal tools: a reviewer has no Write or Edit; grant the smallest set",
    "  that completes the mission.",
    "- Motivated model: mechanical volume → fast model; deep reasoning →",
    "  strong model; otherwise inherit — never a default left by accident.",
    "- The prompt never assumes access to the parent conversation: the agent",
    "  starts fresh and must be told everything it needs.",
    '- Short description, third person, stating when to delegate; "use',
    '  proactively" only when spontaneous delegation is wanted.',
    "",
  ].join("\n");
  const interview = [
    "# Interview bank — sub-agent",
    "",
    "Ask only what the code cannot answer. The five discriminating questions:",
    "",
    "1. Which single task, and how does the agent know it is finished?",
    "2. Does it modify files or only read? (Feeds the minimal tool set.)",
    "3. Spontaneous delegation or on demand? (Feeds the description and",
    '   whether it says "use proactively".)',
    "4. Which context does it need, knowing it starts fresh and sees nothing",
    "   of the parent conversation?",
    "5. Deep reasoning or bulky mechanical work? (Feeds the model choice.)",
    "",
    "Follow up on the output: ask for one example of the exact report the",
    "parent should receive, and write it into the prompt as the required",
    "format.",
    "",
  ].join("\n");
  return { name: "create-agent", skillMd, rubric, interview };
}

function setupContextMeta(): MetaSkill {
  const skillMd = [
    ...frontmatter({
      name: "setup-context",
      description:
        "Builds or improves the AGENTS.md entry point through repo analysis, pre-drafting, a validation interview and line-by-line critique. Use when the user wants to create, improve or complete AGENTS.md or CLAUDE.md, or set up the context AI agents read on the repo.",
      displayName: "Setup Context",
      shortDescription: "Assisted authoring of the AGENTS.md entry point",
      color: "#9D174D",
      icon: "book-open",
      defaultPrompt:
        "Use $setup-context to build or improve AGENTS.md by guided interview.",
    }),
    "# Setup Context",
    "",
    "AGENTS.md is the entry point every agent reads before working; a wrong",
    "line there costs more than an empty file. This meta-skill is /init,",
    "multi-harness and mechanically validated: analyse the repo, pre-draft,",
    "interview only on the non-discoverable, criticize, then write. Six",
    "steps, in order.",
    "",
    "## 1. Inventory before writing",
    "",
    "- Explore the repo first: the REAL build, test and lint commands",
    "  (package.json scripts, Makefile, CI workflows), the directory",
    "  structure, the conventions the code actually follows. Pre-draft the",
    "  stack and product sections from what you find — never ask what the",
    "  code already answers.",
    "- Inventory the existing agent configs — CLAUDE.md, AGENTS.md,",
    "  `.cursor/rules/`, `.cursorrules`, `.github/copilot-instructions.md` —",
    "  and absorb their content into the draft. NEVER overwrite them: they",
    "  hold the team's accumulated instructions; import them, then propose",
    "  retiring the duplicates.",
    "",
    "## 2. Targeted interview",
    "",
    "- Ask ONLY what the repo cannot answer. The bank is in",
    "  references/interview.md: the never-run commands, what the agent got",
    "  wrong recently, the conventions diverging from the ecosystem defaults,",
    "  what is already enforced mechanically, the monorepo layout.",
    "- Run it as a validation interview: show the pre-drafted findings and",
    "  the imported material, and ask the user to confirm, correct and fill",
    "  the gaps — not to dictate a file from scratch.",
    "",
    "## 3. Routing",
    "",
    "- AGENTS.md keeps only what every agent needs on every task. Route the",
    "  rest: a bulky advisory topic becomes a rule listed in the rules index",
    "  (use $create-rule — `agentsdir add rule`); an on-demand workflow is a",
    "  skill ($create-skill); something guaranteed on every event is a hook",
    "  ($create-hook).",
    "- What a linter, the CI or a hook already enforces mechanically is",
    "  EXCLUDED from the file — never send an LLM to do a linter's job.",
    "",
    "## 4. Draft, then critique",
    "",
    "- Draft in the three families of sections: generic (entry-point",
    "  preamble, rules index, verification), stack (exact commands — build,",
    "  targeted test, lint — plus the explicit never-run commands), product",
    "  (what the product is, the key files). Document only what DIVERGES",
    "  from the ecosystem defaults, and point to README and docs — never",
    "  copy them.",
    "- Criticize line by line with the filter",
    '  question: "if this line is deleted, will the agent make a mistake?"',
    "  Remove every line that fails it, and check the draft against every",
    "  criterion of references/rubrique.md.",
    "- Present the result as a revisable proposal — on an existing AGENTS.md,",
    "  as a list of proposed changes — and get the user's go before writing.",
    "",
    "## 5. Generate, then write",
    "",
    "- Blank repo: the skeleton comes from `agentsdir init` (already run",
    "  when this pack is installed) — fill its placeholder sections with the",
    "  approved draft.",
    "- Existing AGENTS.md — improvement mode: apply ONLY the changes the",
    "  user approved and keep the user's sections and wording intact;",
    "  propose, never rewrite.",
    "- Never edit inside the managed blocks (`agentsdir:begin` …",
    "  `agentsdir:end`) — they belong to the CLI. Run `agentsdir sync` after",
    "  writing so the rules index and the projections are regenerated to",
    "  match.",
    "",
    "## 6. Mechanical validation — mandatory",
    "",
    "- Run `agentsdir check`. Any deviation goes back to step 4: never",
    "  conclude with a failing check, and paste the passing check output",
    "  when done.",
    "- Close by suggesting the next steps: $create-skill for the workflows",
    "  the interview surfaced, $create-hook for what must be guaranteed on",
    "  every action.",
    "",
  ].join("\n");
  const rubric = [
    "# AGENTS.md quality rubric",
    "",
    "Criteria marked ▣ are enforced mechanically by `agentsdir check`; the",
    "others belong to the critique pass (step 4).",
    "",
    "## ▣ Mechanical — check fails on these",
    "",
    "- ▣ AGENTS.md exists — `check` fails on a repo without it (run",
    "  `agentsdir init`).",
    "- ▣ The `rules-index` managed block is present and lists exactly the",
    "  rules on disk — regenerated by `sync`, never edited by hand.",
    "- ▣ The CLAUDE.md projection matches AGENTS.md (symlink, or copy kept",
    "  in step by `sync`) — any divergence is reported as projection drift.",
    "",
    "## Critique pass",
    "",
    "- Three families kept: generic sections, stack sections, product",
    "  sections.",
    "- Exact commands (build, targeted test, lint) with the explicit",
    "  never-run commands (watch, deploy) — the non-guessable first.",
    "- Only what diverges from the ecosystem defaults: the model already",
    "  knows the standards.",
    "- Nothing that a linter, the CI or a hook already enforces mechanically.",
    "- No duplication with README or docs: pointers, never copies.",
    "- Existing agent configs imported, never overwritten.",
    "- Short: every line passes the filter",
    '  question: "if this line is deleted, will the agent make a mistake?"',
    "  A false line is worse than no file.",
    "",
  ].join("\n");
  const interview = [
    "# Interview bank — AGENTS.md",
    "",
    "Ask only what the repo cannot answer — the analysis (step 1) answers",
    "the rest. The five discriminating questions:",
    "",
    "1. Which commands exactly (build, targeted test, lint), and which must",
    "   NEVER be run (watch, deploy)? (Feeds the stack sections; every",
    "   command in the file must have been run or confirmed.)",
    "2. What did the agent get wrong recently? (Each observed failure",
    "   becomes the line that would have prevented it.)",
    "3. Which conventions diverge from the ecosystem defaults? (Only the",
    "   divergences are documented — the model already knows the standards.)",
    "4. What is already enforced mechanically — linter, CI, hooks? (It is",
    "   excluded from the file.)",
    "5. Monorepo? Which existing configs (CLAUDE.md, `.cursor/rules/`,",
    "   `.cursorrules`, `.github/copilot-instructions.md`) must be imported?",
    "   (Feeds the inventory and the import.)",
    "",
    "Present each pre-drafted section with its evidence and ask the user to",
    "confirm or correct it — a confirmation is cheaper than a dictation,",
    "and a wrong line is worse than a missing one.",
    "",
  ].join("\n");
  return { name: "setup-context", skillMd, rubric, interview };
}
