import {
  CONVENTIONS_CONSULTED,
  renderConventionsReference,
} from "../core/conventions-dates.js";
import type { PackFile } from "./index.js";

/**
 * Pack `creator`: the meta-skill that judges the FORM of a configuration.
 *
 * The product already answers three questions about an installed
 * configuration, each with its own command, and none of them answers this one:
 * a skill can be perfectly in step with its source, genuinely used and cheap,
 * and still be badly shaped. That is an appreciation, not a measurement — so it
 * is a skill, never a condition in the CLI, exactly as the split between the
 * deterministic and the arguable runs everywhere else in this repo.
 *
 * What keeps it honest is that the norms are NOT the agent's to recall. They
 * are rendered into `references/conventions.md` from `core/conventions-dates.ts`
 * at pack time, each with its source and the day it was read, and the skill is
 * told to quote them from that file. A norm an agent remembers is an opinion
 * with a confident voice; a norm it reads carries a date the reader can argue
 * with. The reference is regenerated by `sync` like any other projection, so a
 * bump of the table reaches installed repositories and `check` reports it if it
 * does not.
 */
export function formSkillFiles(): PackFile[] {
  return [
    {
      path: `${FORM_SKILL_DIR}/SKILL.md`,
      content: renderFormSkill(),
    },
    {
      path: `${FORM_SKILL_DIR}/references/conventions.md`,
      content: renderConventionsReference(),
    },
    {
      path: `${FORM_SKILL_DIR}/references/rubrique.md`,
      content: renderFormRubric(),
    },
    {
      path: `${FORM_SKILL_DIR}/references/interview.md`,
      content: renderFormInterview(),
    },
  ];
}

export const FORM_SKILL = "review-form";
const FORM_SKILL_DIR = `.agents/skills/${FORM_SKILL}`;
const CONVENTIONS_REF = `${FORM_SKILL_DIR}/references/conventions.md`;

/**
 * The four questions, and the one this skill is allowed to answer.
 *
 * They are written into the shipped skill rather than left implicit because
 * mixing them is the failure mode that would make the whole report worthless:
 * "this skill is too long" said in the voice of "this skill has drifted" sends
 * a team to `git diff` for a problem that is not there. Each row names the
 * command that answers it, so the agent has somewhere to send the question
 * instead of answering it itself.
 */
const FOUR_DIAGNOSTICS: readonly string[] = [
  "| Question | Who answers it | How |",
  "| --- | --- | --- |",
  "| Has the configuration **drifted** from its source? | `check` | `agentsdir check` |",
  "| Does it **serve**? | `$review-usage` (pack `usage`) | the usage journal, over enough sessions |",
  "| What does it **cost** in context? | `doctor` | `agentsdir doctor --json`, key `context` |",
  "| Is its **form** still the one recommended? | this skill | the dated norms, read from `references/conventions.md` |",
];

function renderFormSkill(): string {
  return [
    "---",
    `name: ${FORM_SKILL}`,
    // paid at every session, for every skill, by the very norm this skill
    // applies — so it says what the skill is for and stops there
    'description: "Confronts the form of this repo\'s agent configuration with the dated norms this CLI embeds — description and body bounds, progressive disclosure, over-constrained instructions — and proposes changes, each quoting the norm, its source and the day it was read. Use when the user asks whether the configuration is still well shaped, whether a skill should be split or simplified, or whether its practices have aged."',
    "disable-model-invocation: true",
    'display-name: "Review Form"',
    'short-description: "Reviews whether the configuration form still fits"',
    'color: "#0369A1"',
    "icon: badge-check",
    `default-prompt: "Use $${FORM_SKILL} to review whether this repo's agent configuration still has the recommended form."`,
    "implicit: false",
    "---",
    "",
    "# Review Form",
    "",
    "A configuration can be in step with its source, genuinely used and cheap,",
    "and still be badly shaped. Nothing in this product says so — that is what",
    "this skill is for. Produce a Markdown report of **proposals**, each one",
    "quoting the norm it rests on, where that norm comes from, and the day it was",
    "read. Change nothing: the tool proposes, the team decides.",
    "",
    "## 0. Stay inside your question",
    "",
    "Four questions can be asked of an installed configuration. You answer one.",
    "",
    ...FOUR_DIAGNOSTICS,
    "",
    "- **Never mix two rows.** A proposal says one thing about form. If you",
    "  notice drift, usage or cost while reading, write it under",
    "  *Not this report's question* with the command that answers it — never as",
    "  a finding of your own.",
    "- A form problem is never a reason to say an element is unused, expensive or",
    "  out of step, and the reverse holds. They are independent, and a report",
    "  that blurs them sends the team looking in the wrong file.",
    "",
    "## 1. Read the norms before looking at the repo",
    "",
    `- Read \`${CONVENTIONS_REF}\`. It holds every norm this version of the CLI`,
    "  applies, each with its bound, its source and the date that source was read.",
    "- **Quote from that file. Never from memory.** A bound you recall is an",
    "  opinion in a confident voice; a bound you quote carries a date the reader",
    "  can argue with.",
    "- Read the repository the norms speak about first, in this order:",
    "",
    "  ```bash",
    "  mkdir -p .agents/output/form",
    "  agentsdir doctor --json > .agents/output/form/doctor.json",
    "  ```",
    "",
    "- **Nothing creates that directory but you**, and the redirection will not",
    "  create it for you. Use whatever your shell spells it. `.agents/output/`",
    "  is in the managed `.gitignore` block, so nothing written there is",
    "  committed — which is how this report stays inside the repository.",
    "",
    "- The `context.bounds.exceeded` array of that file already lists the size",
    "  bounds this repository crosses, measured exactly. **Take those figures;",
    "  never recount them, never round one.** Your work starts where the",
    "  measurement stops: why the bound is crossed, and what shape would fix it.",
    "",
    "## 2. Inventory the form",
    "",
    "For every `.agents/skills/*/SKILL.md`, every `.agents/agents/*.md` and every",
    "`.agents/rules/*.md`, note what the norms can be applied to:",
    "",
    "- the length of the `description` and of the body, from the doctor file;",
    "- whether the depth sits in the body or in `references/`, and whether the",
    "  body states a procedure or repeats one;",
    "- whether the instructions constrain the agent's steps or state its purpose",
    "  and leave the steps open;",
    "- whether one file covers one subject, or several that never occur together.",
    "",
    "Read the files. An inventory built from filenames judges nothing.",
    "",
    "## 3. Write a proposal, not a verdict",
    "",
    "Every proposal carries, in this order and with nothing missing:",
    "",
    "1. **What to change**, in one sentence, naming the file.",
    "2. **The norm**, quoted from the reference, with its bound when it has one.",
    "3. **Its source and the date it was read**, copied from the reference. A",
    "   proposal without these three is not a proposal: delete it.",
    "4. **The evidence in this repository** — the line, the figure from the",
    "   doctor file, the structure you read. Not an impression.",
    "5. **What it would change and what it would cost**, including when the",
    '   answer is "a little clarity for a morning of work".',
    "",
    "Order the proposals by the weight of their evidence, not by how easy they",
    "are to apply.",
    "",
    "## 4. Say what you cannot say",
    "",
    "- A norm with **no bound** — progressive disclosure, over-constrained",
    "  instructions — is a form, not a size. You are judging, and the report must",
    "  say so in those words. Do not dress an appreciation as a measurement.",
    `- The norms were read on ${CONVENTIONS_CONSULTED} and ship inside this CLI.`,
    "  If you have network access and the source has moved on, report that as a",
    "  finding **about this table** — naming the document, the change and the day",
    "  you read it — and keep the shipped norm as the one you applied. Updating",
    "  the table is a change to the CLI, not to this report.",
    "- If nothing crosses a norm, say exactly that. A report that manufactures",
    "  three proposals to look useful costs more than it gives.",
    "",
    "## 5. Nothing leaves the repository",
    "",
    "- Write the report to `.agents/output/form/review-<YYYY-MM-DD>.md`, which",
    "  git ignores.",
    "- Send nothing anywhere: no upload, no issue, no paste into a third-party",
    "  tool, no query to a registry to check a version. The CLI itself opens no",
    "  connection, and a test proves it — do not be the part that does.",
    "- **Apply nothing.** Edit no `SKILL.md`, run no `agentsdir sync`, delete",
    "  nothing. If the team accepts a proposal, they run the change themselves,",
    "  and `check` then has the last word.",
    "",
    "## Verification",
    "",
    "Before handing the report over, check every line of it:",
    "",
    "- every proposal quotes a norm, a source and a date;",
    "- no proposal answers drift, usage or cost;",
    "- every figure comes from the doctor file, unrounded;",
    "- no file of the repository was modified;",
    `- the rubric in \`${FORM_SKILL_DIR}/references/rubrique.md\` passes on every`,
    "  section.",
    "",
  ].join("\n");
}

function renderFormRubric(): string {
  return [
    "# Rubric — a report on form",
    "",
    "Run it on the finished report, section by section. A failing line is",
    "rewritten, never explained away.",
    "",
    "## Each proposal",
    "",
    "- [ ] Names one file and one change, in one sentence.",
    "- [ ] Quotes a norm from `references/conventions.md`, not from memory.",
    "- [ ] Carries that norm's source **and** the day it was read.",
    "- [ ] Rests on something read in this repository — a line, a structure, a",
    "      figure taken from `doctor --json` — never on an impression.",
    "- [ ] States what the change would cost, not only what it would give.",
    "- [ ] Says plainly when it is a judgement rather than a bound crossed.",
    "",
    "## The report as a whole",
    "",
    "- [ ] Answers the form question and no other. Drift, usage and cost appear",
    "      only under *Not this report's question*, each with its command.",
    "- [ ] Repeats no figure the context budget already published, and rounds",
    "      none of them.",
    "- [ ] Says how old the embedded norms are.",
    "- [ ] Proposes nothing it has already applied — because it has applied",
    "      nothing.",
    "- [ ] Ends without a summary that implies a decision the team has not taken.",
    "",
    "## Refusals that count as success",
    "",
    "- No norm is crossed, and the report says so in a line instead of inventing",
    "  work.",
    "- A norm has no bound and the repository's case is genuinely borderline: the",
    "  report says it is borderline and leaves it.",
    "- `doctor --json` carries no `context` key: the sizes were not measured, the",
    "  report says so, and it does not treat an unmeasured size as a small one.",
    "",
  ].join("\n");
}

function renderFormInterview(): string {
  return [
    "# Interview — before judging a form",
    "",
    "Ask these when the answer would change a proposal. Skip the rest: an",
    "interview that asks everything is a questionnaire, and it gets abandoned.",
    "",
    "## On a skill that crosses a size bound",
    "",
    "- What does this skill do that a shorter one could not? If the answer is a",
    "  list, the list is the split.",
    "- Which part of the body is read every time it runs, and which part is read",
    "  only in one case? The second part belongs in `references/`.",
    "- Was the length deliberate — a procedure that genuinely has thirty steps —",
    "  or did it grow one paragraph at a time?",
    "",
    "## On an instruction that may be over-constrained",
    "",
    "- Does this line tell the agent what to achieve, or which keystrokes to",
    "  use? The second ages with the tools.",
    "- Has this constraint ever prevented a mistake you actually saw? If nobody",
    "  remembers one, it is a habit, not a rule.",
    "- If this line were deleted, would the agent make a mistake?",
    "",
    "## On the norms themselves",
    "",
    "- Do you want the report to apply the norms this CLI ships, or to flag",
    "  where they look out of date? Both are legitimate; they produce different",
    "  reports.",
    "- Is there a house convention that deliberately departs from a norm? Say so",
    "  now: a proposal against a decision the team already took is noise.",
    "",
  ].join("\n");
}
