import {
  USAGE_JOURNAL_DIR,
  USAGE_RETENTION_DAYS,
} from "../core/usage-journal.js";
import type { PackFile } from "./index.js";

/**
 * Pack `usage`, stage 2: the review.
 *
 * Stage 1 writes a journal and passes no judgement. This stage turns it into
 * a report that says three things, and the third matters most: what is used,
 * what was never seen, and **what the measure cannot say**. Without that last
 * part the reader credits the numbers with an authority they have not got —
 * above all for rules, which are not invocable at all.
 *
 * The split inside this stage mirrors the split between the two: a script
 * counts (deterministic, testable byte for byte, and it keeps a month of JSONL
 * out of the context window), and a meta-skill judges. Neither deletes
 * anything: the tool proposes, the team decides.
 */
export function reviewSkillFiles(): PackFile[] {
  return [
    {
      path: `${REVIEW_SKILL_DIR}/SKILL.md`,
      content: renderReviewSkill(),
    },
    {
      path: `${REVIEW_SKILL_DIR}/scripts/${SUMMARIZE_SCRIPT}`,
      content: renderSummarizeScript(),
    },
    {
      path: `${REVIEW_SKILL_DIR}/references/rubrique.md`,
      content: renderReviewRubric(),
    },
    {
      path: `${REVIEW_SKILL_DIR}/references/interview.md`,
      content: renderReviewInterview(),
    },
  ];
}

export const REVIEW_SKILL = "review-usage";
const REVIEW_SKILL_DIR = `.agents/skills/${REVIEW_SKILL}`;
const SUMMARIZE_SCRIPT = "summarize.mjs";
const SCRIPT_PATH = `${REVIEW_SKILL_DIR}/scripts/${SUMMARIZE_SCRIPT}`;

/**
 * The volume below which the review refuses to conclude on an ABSENCE.
 *
 * The asymmetry is the whole point: a presence is proved by one line, an
 * absence is not. Both conditions are required — twenty sessions crammed into
 * one afternoon say nothing about a skill that only serves at release time,
 * and fourteen days holding three sessions say nothing at all. Below either,
 * the "never seen" table is replaced by a refusal naming what is missing,
 * while the "what was used" table is printed regardless.
 */
const MIN_SESSIONS = 20;
const MIN_DAYS = 14;

/**
 * What the harness does today, with the primary source and the date it was
 * read. It belongs in the shipped skill because it is the strongest argument
 * for the whole report: the arbitration already happens, silently, and this
 * makes it visible and arguable. The skill tells the agent to re-read the
 * page before quoting it — this is exactly the kind of fact that moves.
 */
const HARNESS_FACTS: readonly string[] = [
  "- The combined `description` and `when_to_use` of a skill is **truncated at",
  "  1,536 characters in the skill listing to reduce context usage**.",
  "- After a conversation is summarized, Claude Code re-attaches the most",
  "  recent invocation of each skill, keeping the first 5,000 tokens of each,",
  "  within a **combined 25,000-token budget filled starting from the most",
  "  recently invoked skill** — so older skills **can be dropped entirely**",
  "  when many were invoked in one session.",
  "- Source: code.claude.com/docs/en/skills, read on 2026-09-13. Re-read it",
  "  before quoting it: this behaviour moves with the harness.",
];

function renderReviewSkill(): string {
  return [
    "---",
    `name: ${REVIEW_SKILL}`,
    'description: "Turns the usage journal into a review of what the repo configuration is actually used for: what serves, what was never seen, what the measure cannot say, and what each element costs per session. Use when the user asks whether the skills, sub-agents or rules are worth keeping, what to prune, or what the usage journal shows."',
    "disable-model-invocation: true",
    'display-name: "Review Usage"',
    'short-description: "Reviews what the configuration is used for"',
    'color: "#0F766E"',
    "icon: clipboard-list",
    `default-prompt: "Use $${REVIEW_SKILL} to review what this repo's agent configuration is actually used for."`,
    "implicit: false",
    "---",
    "",
    "# Review Usage",
    "",
    "The `usage` pack observes; this turns the observation into a decision the",
    "team can take. Produce a Markdown review saying what serves, what was never",
    "seen, and — the section nobody else writes — **what the measure cannot",
    "say**. Nothing is ever deleted here: every removal is a proposal carrying",
    "the data that motivates it.",
    "",
    "## 1. Count before judging",
    "",
    "- Run the script; it does the arithmetic and keeps a month of JSONL out of",
    "  the context window:",
    "",
    "  ```bash",
    "  agentsdir doctor --json > .agents/output/usage/doctor.json",
    `  node ${SCRIPT_PATH} --doctor .agents/output/usage/doctor.json`,
    "  ```",
    "",
    "- Take its Markdown output as the factual base of the review. Never retype",
    "  a count, never round one, and never add a number it did not produce.",
    "- If `agentsdir doctor` emits no `context` key, the cost was not measured.",
    "  Say so in the review. **Never treat an unmeasured cost as a zero cost.**",
    "- Run the script with no `--doctor` file only when the budget is genuinely",
    "  unavailable; the crossing is what makes the review actionable.",
    "",
    "## 2. Honour the verdict on volume",
    "",
    `- The script prints whether the journal reaches ${MIN_SESSIONS} sessions over`,
    `  ${MIN_DAYS} distinct days. When it does **not**, the review reports what was`,
    "  observed and **refuses to conclude that anything is unused**. Say what is",
    "  missing and come back later; do not soften it into a suggestion.",
    "- The asymmetry is deliberate and belongs in the review: **a presence is",
    "  proved by a single line, an absence needs volume.** So the list of what",
    "  WAS used is always valid, whatever the volume.",
    "",
    "## 3. Interview what the journal cannot know",
    "",
    "- Ask only what no line can answer — the bank is in",
    "  references/interview.md: was collection suspended, which harnesses do",
    "  people actually use, was there a release or a holiday in the window,",
    "  do the `exclude` globs overlap a rule's scope.",
    "- Every answer belongs in the limits section, not as decoration: a harness",
    "  used without these hooks installed leaves no trace at all, and a skill",
    "  that only serves during a release looks dead in a quiet fortnight.",
    "",
    "## 4. Write the review, in four sections",
    "",
    "- **What is used** — per skill and sub-agent: occurrences, sessions, last",
    "  seen, and the cost crossing. Ranked by occurrences.",
    "- **What was never seen** — only above the threshold. Each line carries the",
    "  volume it rests on and what it costs per session, and is phrased as a",
    "  proposal: *consider removing*, never *removed*.",
    "- **Rule relevance** — see section 5; it has its own vocabulary.",
    "- **What this measure cannot say** — see section 6; it is mandatory.",
    "",
    "## 5. Rules: relevance, never usage",
    "",
    "- **A rule is not invocable.** No hook can say whether an agent read one.",
    "  Write `relevant` / `never relevant`, and NEVER `used`, `invoked`, `read`",
    "  or `unread` about a rule. State this limit in the review itself.",
    "- A scoped rule whose globs met a touched path is **relevant**, with its",
    "  count and its last occurrence. A scoped rule whose globs never met one is",
    "  **never relevant** over the window — a real, actionable finding.",
    "- A rule with **no** `paths:` has no scope to meet: it is neither, and it",
    "  goes in the limits section. It is also paid at every session, which is",
    "  precisely why it deserves a line rather than silence.",
    "",
    "## 6. What this measure cannot say — mandatory section",
    "",
    "- Reproduce every mechanical limit the script printed, and add what the",
    "  interview turned up. A review without this section is worse than no",
    "  review: it looks authoritative.",
    "- At minimum: rules are not observable (relevance only); an invocation says",
    "  a skill ran, never that it helped; a harness whose hooks are not",
    "  installed leaves nothing; excluded and out-of-repo paths are recorded as",
    `  null, so a rule scoped to them can never appear relevant; the journal`,
    `  holds ${USAGE_RETENTION_DAYS} days, so anything older is gone; a period with`,
    "  `enabled = false` left no trace; and if the script reports delegations",
    "  without an agent name, sub-agent counts are unreliable — say so instead",
    "  of reporting those sub-agents as never delegated to.",
    "",
    "## 7. Cross usage with cost, and say why it matters",
    "",
    "- The two figures answer the only question a team asks: **is this skill",
    "  worth what it costs?** A skill never invoked whose metadata costs a few",
    "  tokens per session is not worth a discussion; the same at several hundred",
    "  is an obvious candidate.",
    "- Keep the two costs apart, as the script does: what an element costs at",
    "  **every session**, and what it costs **per invocation**. A skill that is",
    "  never invoked costs its metadata always and its body never; adding the",
    "  two would produce the impressive, false total the budget report exists to",
    "  avoid.",
    "- Close on the argument that justifies the whole exercise: the harness",
    "  already arbitrates this in silence.",
    ...HARNESS_FACTS,
    "  The review makes a decision the harness takes in the team's back visible",
    "  and arguable.",
    "",
    "## 8. Hand over without deciding",
    "",
    "- Write the review to `.agents/output/usage/review-<YYYY-MM-DD>.md`. That",
    "  directory is git-ignored, and the review carries the same sensitivity as",
    "  the journal it summarizes.",
    "- Delete nothing, and run no `pack remove`. Present the proposals and stop.",
    "  If the user accepts one, the removal is theirs to run.",
    "",
  ].join("\n");
}

function renderReviewRubric(): string {
  return [
    "# Usage review quality rubric",
    "",
    "Criteria marked ▣ are produced mechanically by",
    `\`${SUMMARIZE_SCRIPT}\`; the others belong to the writing pass.`,
    "",
    "## ▣ Mechanical",
    "",
    "- ▣ Every count, date and cost comes from the script. No figure is retyped,",
    "  rounded or invented.",
    `- ▣ The observation volume is stated: sessions, distinct days, window.`,
    `- ▣ Below ${MIN_SESSIONS} sessions or ${MIN_DAYS} distinct days, no absence is`,
    "  concluded — the refusal replaces the table and names what is missing.",
    "",
    "## Writing pass",
    "",
    "- The review has the four sections, and the limits section is never the one",
    "  that gets cut for length.",
    "- Rules are spoken of as relevant or never relevant, never as used or read,",
    "  and the reason is stated in the review.",
    "- A rule with no `paths:` is in the limits section, not among the dead",
    "  rules.",
    "- Every removal proposal carries its data — sessions observed, last",
    "  occurrence, cost per session — and is worded as a proposal.",
    "- Nothing is deleted, and no `pack remove` is run.",
    "- The cost crossing keeps per-session and per-invocation apart, and an",
    "  unmeasured cost is reported as unmeasured, never as zero.",
    "- Sub-agent counts are qualified when the journal holds unnamed",
    "  delegations.",
    "- The review is readable in a terminal and in a code review: tables, short",
    "  lines, no decoration.",
    "",
  ].join("\n");
}

function renderReviewInterview(): string {
  return [
    "# Interview bank — usage review",
    "",
    "Ask only what no journal line can answer. Two or three questions, before",
    "the review is written. Every answer lands in the limits section.",
    "",
    "| Question | What it changes |",
    "| --- | --- |",
    "| Was collection suspended during the window (`enabled = false`), or the pack reinstalled? | A gap in the journal is not an absence of work |",
    "| Which harnesses does the team actually use day to day? | A harness whose hooks are not installed leaves no trace; its sessions are invisible |",
    "| Did the window hold a release, a freeze, a holiday or a long-running branch? | A skill that only serves at release time looks dead in a quiet fortnight |",
    "| Do the `[usage].exclude` globs overlap the scope of a rule? | An excluded path is journalled as null, so that rule can never appear relevant |",
    "| Who ran sessions on this repo — the whole team, or one person? | One person's habits are not the team's usage |",
    "| Is any skill invoked by a script or a CI job rather than by a session? | Such an invocation never passes through a harness hook |",
    "",
    "Record each answer with the question, and carry it into the limits section",
    "verbatim. An answer paraphrased into a conclusion is how a limit becomes a",
    "claim.",
    "",
  ].join("\n");
}

/**
 * The mechanical half, as a dependency-free Node script.
 *
 * Why a script rather than instructions telling the agent to read the journal:
 * a month of sessions is thousands of JSONL lines, and pouring them into the
 * context window to count them would be the very waste the context budget
 * exists to expose (docs/conventions.md §10). It prints Markdown by default —
 * the sections that are pure arithmetic — and JSON under `--json`. It reads,
 * counts, and writes nothing.
 */
function renderSummarizeScript(): string {
  const journalSegments = USAGE_JOURNAL_DIR.split("/")
    .map((segment) => JSON.stringify(segment))
    .join(", ");
  return [
    "// Usage review, mechanical part — installed by `agentsdir pack add usage`.",
    "//",
    "// Reads the journal specified in docs/conventions.md §9 and prints what is",
    "// pure arithmetic: the observation volume, what was invoked, what was never",
    "// seen, which rules were relevant, and what the measure cannot say.",
    "//",
    "// Usage:",
    `//   node ${SCRIPT_PATH} [--json] [--doctor <file>]`,
    "//",
    "//   --json           machine output instead of Markdown",
    "//   --doctor <file>  output of `agentsdir doctor --json`, to cross usage",
    "//                    with cost. Without it the review says the cost was",
    "//                    not measured — never that it is zero.",
    "//",
    "// Read-only, zero dependency, and it holds no opinion: the skill that runs",
    "// it writes the conclusions.",
    "",
    'import { readdirSync, readFileSync, statSync } from "node:fs";',
    'import { dirname, join, resolve } from "node:path";',
    'import { fileURLToPath } from "node:url";',
    "",
    "// .agents/skills/<skill>/scripts/ sits four levels below the repo root.",
    "const ROOT = resolve(",
    "  dirname(fileURLToPath(import.meta.url)),",
    '  "..",',
    '  "..",',
    '  "..",',
    '  "..",',
    ");",
    `const JOURNAL_DIR = join(ROOT, ${journalSegments});`,
    `const MIN_SESSIONS = ${MIN_SESSIONS};`,
    `const MIN_DAYS = ${MIN_DAYS};`,
    `const RETENTION_DAYS = ${USAGE_RETENTION_DAYS};`,
    "",
    'const NEWLINE = "\\n";',
    "const JOURNAL_NAME = /^usage-\\d{4}-\\d{2}-\\d{2}\\.jsonl$/;",
    "const FRONTMATTER = /^---\\r?\\n([\\s\\S]*?)\\r?\\n---(?:\\r?\\n|$)/;",
    "const ASSIGNMENT = /^([A-Za-z-]+)\\s*=\\s*(.+)$/;",
    'const QUOTED = /"([^"]*)"/g;',
    "",
    "main();",
    "",
    "function main() {",
    "  const args = process.argv.slice(2);",
    '  const asJson = args.includes("--json");',
    '  const at = args.indexOf("--doctor");',
    "  const report = build(readDoctor(at === -1 ? null : (args[at + 1] ?? null)));",
    "  process.stdout.write(",
    "    asJson ? JSON.stringify(report, null, 2) + NEWLINE : render(report),",
    "  );",
    "}",
    "",
    "function build(cost) {",
    "  const entries = readJournal();",
    "  return {",
    "    volume: measureVolume(entries),",
    "    skills: reviewSkills(entries, cost),",
    "    agents: reviewAgents(entries, cost),",
    "    rules: reviewRules(entries, cost),",
    "    limits: measureLimits(entries, cost),",
    "  };",
    "}",
    "",
    "/**",
    " * Every journal line, malformed ones skipped. A truncated last line is",
    " * ordinary — a session can be killed mid-append — and is no reason to",
    " * refuse the whole window.",
    " */",
    "function readJournal() {",
    "  const entries = [];",
    "  for (const name of journalFiles()) {",
    "    let raw;",
    "    try {",
    '      raw = readFileSync(join(JOURNAL_DIR, name), "utf8");',
    "    } catch {",
    "      continue;",
    "    }",
    "    for (const line of raw.split(NEWLINE)) {",
    '      if (line.trim() === "") continue;',
    "      let parsed;",
    "      try {",
    "        parsed = JSON.parse(line);",
    "      } catch {",
    "        continue;",
    "      }",
    '      if (typeof parsed !== "object" || parsed === null) continue;',
    '      if (typeof parsed.ts !== "string") continue;',
    "      entries.push(parsed);",
    "    }",
    "  }",
    "  return entries;",
    "}",
    "",
    "function journalFiles() {",
    "  try {",
    "    return readdirSync(JOURNAL_DIR)",
    "      .filter((name) => JOURNAL_NAME.test(name))",
    "      .sort();",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "/**",
    " * The volume the whole review rests on, and the single verdict deciding",
    " * whether an absence may be concluded from it. Both conditions, never one.",
    " */",
    "function measureVolume(entries) {",
    "  const sessions = new Set();",
    "  const days = new Set();",
    "  let first = null;",
    "  let last = null;",
    "  for (const entry of entries) {",
    "    if (entry.session) sessions.add(entry.session);",
    "    days.add(entry.ts.slice(0, 10));",
    "    if (first === null || entry.ts < first) first = entry.ts;",
    "    if (last === null || entry.ts > last) last = entry.ts;",
    "  }",
    "  return {",
    "    sessions: sessions.size,",
    "    days: days.size,",
    "    lines: entries.length,",
    "    files: journalFiles().length,",
    "    first,",
    "    last,",
    "    threshold: { sessions: MIN_SESSIONS, days: MIN_DAYS },",
    "    conclusive: sessions.size >= MIN_SESSIONS && days.size >= MIN_DAYS,",
    "  };",
    "}",
    "",
    "function reviewSkills(entries, cost) {",
    "  const counts = tally(entries, (entry) => entry.skill);",
    '  return listDirs(join(ROOT, ".agents", "skills"))',
    "    .map((name) => ({",
    "      name,",
    "      ...(counts.get(name) ?? zero()),",
    "      ...skillCost(cost, name),",
    "    }))",
    "    .sort(byUseThenName);",
    "}",
    "",
    "function reviewAgents(entries, cost) {",
    "  const counts = tally(entries, (entry) => entry.agent);",
    '  return listFiles(join(ROOT, ".agents", "agents"))',
    "    .map((file) => {",
    "      const name = agentName(file);",
    "      return {",
    "        name,",
    "        file,",
    "        ...(counts.get(name) ?? zero()),",
    '        ...pathCost(cost, ".agents/agents/" + file),',
    "      };",
    "    })",
    "    .sort(byUseThenName);",
    "}",
    "",
    "/**",
    " * Rules, in three buckets — never two.",
    " *",
    " * A rule is not invocable: no hook can say whether an agent read one. What",
    " * the journal supports is RELEVANCE, so a scoped rule whose globs met a",
    " * touched path is `relevant`, and one whose globs never did is",
    " * `never-relevant`. A rule with no `paths:` has no scope to meet: it is",
    " * neither, and it goes to `cannot-say` — where it belongs, since it is also",
    " * paid at every session.",
    " */",
    "function reviewRules(entries, cost) {",
    "  const touched = entries.filter(",
    '    (entry) => typeof entry.path === "string" && entry.path !== "",',
    "  );",
    '  return listFiles(join(ROOT, ".agents", "rules"))',
    "    .map((file) => {",
    '      const globs = readScope(join(ROOT, ".agents", "rules", file));',
    "      const sessions = new Set();",
    "      let matches = 0;",
    "      let lastSeen = null;",
    "      for (const entry of touched) {",
    "        if (!globs.some((glob) => matchGlob(glob, entry.path))) continue;",
    "        matches += 1;",
    "        if (entry.session) sessions.add(entry.session);",
    "        if (lastSeen === null || entry.ts > lastSeen) lastSeen = entry.ts;",
    "      }",
    "      return {",
    "        file,",
    "        globs,",
    "        matches,",
    "        sessions: sessions.size,",
    "        lastSeen,",
    "        bucket: ruleBucket(globs.length, matches),",
    '        ...pathCost(cost, ".agents/rules/" + file),',
    "      };",
    "    })",
    "    .sort((a, b) => b.matches - a.matches || compare(a.file, b.file));",
    "}",
    "",
    "function ruleBucket(scopes, matches) {",
    '  if (scopes === 0) return "cannot-say";',
    '  return matches > 0 ? "relevant" : "never-relevant";',
    "}",
    "",
    "/**",
    " * What the numbers above must not be read as. Every entry here exists",
    " * because a reader who does not see it credits the review with an authority",
    " * it has not got.",
    " */",
    "function measureLimits(entries, cost) {",
    "  let delegations = 0;",
    "  let unnamed = 0;",
    "  let toolCalls = 0;",
    "  let withoutPath = 0;",
    "  for (const entry of entries) {",
    '    if (entry.event === "SubagentStart" || entry.event === "SubagentStop") {',
    "      delegations += 1;",
    "      if (!entry.agent) unnamed += 1;",
    "    }",
    '    if (entry.event === "PreToolUse") {',
    "      toolCalls += 1;",
    "      if (!entry.path) withoutPath += 1;",
    "    }",
    "  }",
    "  const config = readConfig();",
    "  return {",
    "    delegations,",
    "    unnamedDelegations: unnamed,",
    "    toolCalls,",
    "    toolCallsWithoutPath: withoutPath,",
    "    excludeGlobs: config.exclude,",
    "    collectionEnabled: config.enabled,",
    "    retentionDays: RETENTION_DAYS,",
    '    cost: cost === null ? "not-measured" : "measured",',
    "  };",
    "}",
    "",
    "function tally(entries, pick) {",
    "  const counts = new Map();",
    "  for (const entry of entries) {",
    "    const key = pick(entry);",
    '    if (typeof key !== "string" || key === "") continue;',
    "    let found = counts.get(key);",
    "    if (found === undefined) {",
    "      found = { occurrences: 0, sessions: 0, lastSeen: null, seen: new Set() };",
    "      counts.set(key, found);",
    "    }",
    "    found.occurrences += 1;",
    "    if (entry.session) found.seen.add(entry.session);",
    "    found.sessions = found.seen.size;",
    "    if (found.lastSeen === null || entry.ts > found.lastSeen) {",
    "      found.lastSeen = entry.ts;",
    "    }",
    "  }",
    "  for (const found of counts.values()) delete found.seen;",
    "  return counts;",
    "}",
    "",
    "function zero() {",
    "  return { occurrences: 0, sessions: 0, lastSeen: null };",
    "}",
    "",
    "function byUseThenName(a, b) {",
    "  return b.occurrences - a.occurrences || compare(a.name, b.name);",
    "}",
    "",
    "function compare(a, b) {",
    "  return a < b ? -1 : a > b ? 1 : 0;",
    "}",
    "",
    "/** The items of `agentsdir doctor --json`, or null when unavailable. */",
    "function readDoctor(file) {",
    "  if (file === null) return null;",
    "  try {",
    '    const raw = readFileSync(file, "utf8").replace(/^\uFEFF/, "");',
    "    const parsed = JSON.parse(raw);",
    "    const items = parsed && parsed.context && parsed.context.items;",
    "    return Array.isArray(items) ? items : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "/**",
    " * The crossing, and its one subtlety: a skill that is never invoked costs",
    " * its metadata at EVERY session and its body never. Adding the two would",
    " * reproduce the impressive, false total the budget report exists to avoid,",
    " * so they stay apart — per session, and per invocation.",
    " */",
    "function skillCost(items, name) {",
    "  if (items === null) return { perSession: null, perInvocation: null };",
    '  const prefix = ".agents/skills/" + name + "/";',
    "  let perSession = 0;",
    "  let perInvocation = 0;",
    "  for (const item of items) {",
    "    if (!item.path.startsWith(prefix)) continue;",
    '    if (item.when === "always") perSession += item.tokens;',
    "    else perInvocation += item.tokens;",
    "  }",
    "  return { perSession, perInvocation };",
    "}",
    "",
    "/** Same split, for an element that is one file: a rule, a sub-agent. */",
    "function pathCost(items, path) {",
    "  if (items === null) return { perSession: null, perInvocation: null };",
    "  let perSession = 0;",
    "  let perInvocation = 0;",
    "  for (const item of items) {",
    "    if (item.path !== path) continue;",
    '    if (item.when === "always") perSession += item.tokens;',
    "    else perInvocation += item.tokens;",
    "  }",
    "  return { perSession, perInvocation };",
    "}",
    "",
    "function listDirs(dir) {",
    "  try {",
    "    return readdirSync(dir)",
    "      .filter((name) => {",
    "        try {",
    "          return statSync(join(dir, name)).isDirectory();",
    "        } catch {",
    "          return false;",
    "        }",
    "      })",
    "      .sort();",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "function listFiles(dir) {",
    "  try {",
    '    return readdirSync(dir).filter((name) => name.endsWith(".md")).sort();',
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "function agentName(file) {",
    "  try {",
    '    const source = readFileSync(join(ROOT, ".agents", "agents", file), "utf8");',
    "    const block = FRONTMATTER.exec(source);",
    "    const name = block === null ? null : /^name:\\s*(.+)$/m.exec(block[1]);",
    "    return name === null ? file.slice(0, -3) : unquote(name[1].trim());",
    "  } catch {",
    "    return file.slice(0, -3);",
    "  }",
    "}",
    "",
    "/** The `paths:` globs of a rule frontmatter; an empty list means unscoped. */",
    "function readScope(file) {",
    "  let source;",
    "  try {",
    '    source = readFileSync(file, "utf8");',
    "  } catch {",
    "    return [];",
    "  }",
    "  const block = FRONTMATTER.exec(source);",
    "  if (block === null) return [];",
    "  const globs = [];",
    "  let inPaths = false;",
    "  for (const line of block[1].split(NEWLINE)) {",
    "    if (/^paths:/.test(line)) {",
    "      inPaths = true;",
    "      continue;",
    "    }",
    "    if (!inPaths) continue;",
    "    const item = /^\\s+-\\s*(.+)$/.exec(line);",
    "    if (item === null) break;",
    "    globs.push(unquote(item[1].trim()));",
    "  }",
    "  return globs;",
    "}",
    "",
    "function unquote(value) {",
    '  return value.replace(/^["\']/, "").replace(/["\']$/, "");',
    "}",
    "",
    "/** `[usage]` of .agents.toml — the same minimal reader as the collector. */",
    "function readConfig() {",
    "  const config = { enabled: true, exclude: [] };",
    "  let raw;",
    "  try {",
    '    raw = readFileSync(join(ROOT, ".agents.toml"), "utf8");',
    "  } catch {",
    "    return config;",
    "  }",
    '  let section = "";',
    "  for (const line of raw.split(NEWLINE)) {",
    "    const trimmed = line.trim();",
    '    if (trimmed.startsWith("[")) {',
    "      section = trimmed;",
    "      continue;",
    "    }",
    '    if (section !== "[usage]") continue;',
    "    const match = ASSIGNMENT.exec(trimmed);",
    "    if (match === null) continue;",
    '    if (match[1] === "enabled") config.enabled = match[2].trim() === "true";',
    '    if (match[1] === "exclude") {',
    "      config.exclude = [...match[2].matchAll(QUOTED)].map((m) => m[1]);",
    "    }",
    "  }",
    "  return config;",
    "}",
    "",
    "// The glob semantics of `add rule --paths`, identical to the collector's:",
    "// the scope a rule declares and the paths the journal kept have to be",
    "// compared under one set of rules, or relevance is measured against another.",
    "function matchGlob(glob, value) {",
    "  const pattern = glob",
    '    .replace(/[.+^${}()|[\\]\\\\]/g, "\\\\$&")',
    '    .replace(/\\*\\*\\//g, "\\u0000")',
    '    .replace(/\\*\\*/g, "\\u0001")',
    '    .replace(/\\*/g, "[^/]*")',
    '    .replace(/\\?/g, "[^/]")',
    '    .replace(/\\u0000/g, "(?:.*/)?")',
    '    .replace(/\\u0001/g, ".*");',
    '  return new RegExp("^" + pattern + "$").test(value);',
    "}",
    "",
    ...renderMarkdownSections(),
  ].join("\n");
}

/**
 * The Markdown rendering, kept apart so the arithmetic above stays readable.
 * Emitted into the same script; the agent never reformats these numbers.
 */
function renderMarkdownSections(): string[] {
  return [
    "/** The mechanical half of the review, as Markdown. */",
    "function render(report) {",
    "  const out = [];",
    '  out.push("# Usage review — mechanical findings", "");',
    "  out.push(",
    `    "Produced by \\\`${SUMMARIZE_SCRIPT}\\\`. Counts only: the judgement, the",`,
    '    "interview answers and the proposals belong to the review that embeds",',
    '    "this.",',
    '    "",',
    "  );",
    "  out.push(...renderVolume(report.volume));",
    "  out.push(...renderUsed(report));",
    "  out.push(...renderNeverSeen(report));",
    "  out.push(...renderRules(report.rules));",
    "  out.push(...renderLimits(report));",
    "  return out.join(NEWLINE) + NEWLINE;",
    "}",
    "",
    "function renderVolume(volume) {",
    "  const out = [];",
    '  out.push("## Observation volume", "");',
    '  out.push("| Measure | Value |", "| --- | --- |");',
    '  out.push("| Sessions observed | " + volume.sessions + " |");',
    '  out.push("| Distinct days | " + volume.days + " |");',
    '  out.push("| Journal lines | " + volume.lines + " |");',
    '  out.push("| Journal files | " + volume.files + " |");',
    '  out.push("| Window | " + windowOf(volume) + " |");',
    '  out.push("");',
    "  if (volume.conclusive) {",
    "    out.push(",
    '      "Threshold to conclude on an absence: " + MIN_SESSIONS + " sessions over " +',
    '        MIN_DAYS + " distinct days. **Met.**",',
    '      "",',
    "    );",
    "  } else {",
    "    out.push(",
    '      "Threshold to conclude on an absence: " + MIN_SESSIONS + " sessions over " +',
    '        MIN_DAYS + " distinct days. **Not met** — " + volume.sessions +',
    '        " session(s) over " + volume.days + " day(s).",',
    '      "",',
    '      "**No absence is concluded below.** What follows lists what WAS",',
    '      "observed, which one line is enough to prove; concluding that anything",',
    '      "is unused needs volume this journal has not got. Come back when it has.",',
    '      "",',
    "    );",
    "  }",
    "  return out;",
    "}",
    "",
    "function windowOf(volume) {",
    '  if (volume.first === null) return "empty journal";',
    '  return volume.first.slice(0, 10) + " to " + volume.last.slice(0, 10);',
    "}",
    "",
    "function renderUsed(report) {",
    "  const skills = report.skills.filter((row) => row.occurrences > 0);",
    "  const agents = report.agents.filter((row) => row.occurrences > 0);",
    "  const out = [];",
    '  out.push("## What was used", "");',
    "  if (skills.length === 0 && agents.length === 0) {",
    '    out.push("No skill invocation and no delegation in the window.", "");',
    "    return out;",
    "  }",
    "  if (skills.length > 0) {",
    '    out.push("### Skills", "");',
    "    out.push(...table(skills));",
    "  }",
    "  if (agents.length > 0) {",
    '    out.push("### Sub-agents", "");',
    "    out.push(...table(agents));",
    "  }",
    "  return out;",
    "}",
    "",
    "function renderNeverSeen(report) {",
    "  const out = [];",
    '  out.push("## What was never seen", "");',
    "  if (!report.volume.conclusive) {",
    "    out.push(",
    '      "Not concluded: the journal is below the threshold stated above. A",',
    '      "presence is proved by one line, an absence is not.",',
    '      "",',
    "    );",
    "    return out;",
    "  }",
    "  const skills = report.skills.filter((row) => row.occurrences === 0);",
    "  const agents = report.agents.filter((row) => row.occurrences === 0);",
    "  if (skills.length === 0 && agents.length === 0) {",
    '    out.push("Every installed skill and sub-agent was seen at least once.", "");',
    "    return out;",
    "  }",
    "  out.push(",
    '    "Never seen over " + report.volume.sessions + " sessions and " +',
    '      report.volume.days + " days. Each line is a CANDIDATE for removal.",',
    '    "Nothing here is decided, and nothing is deleted.",',
    '    "",',
    "  );",
    "  if (skills.length > 0) {",
    '    out.push("### Skills", "");',
    "    out.push(...table(skills));",
    "  }",
    "  if (agents.length > 0) {",
    '    out.push("### Sub-agents", "");',
    "    out.push(...table(agents));",
    "  }",
    "  return out;",
    "}",
    "",
    "function table(rows) {",
    "  const out = [",
    '    "| Name | Occurrences | Sessions | Last seen | Cost per session | Cost per invocation |",',
    '    "| --- | --- | --- | --- | --- | --- |",',
    "  ];",
    "  for (const row of rows) {",
    "    out.push(",
    '      "| " + row.name + " | " + row.occurrences + " | " + row.sessions +',
    '        " | " + (row.lastSeen === null ? "never" : row.lastSeen.slice(0, 10)) +',
    '        " | " + tokens(row.perSession) + " | " + tokens(row.perInvocation) + " |",',
    "    );",
    "  }",
    '  out.push("");',
    "  return out;",
    "}",
    "",
    "function tokens(value) {",
    '  return value === null ? "not measured" : "~" + value + " tokens";',
    "}",
    "",
    "/**",
    " * Rules speak of RELEVANCE and never of usage. The vocabulary is the point:",
    " * nothing can observe whether an agent read a rule, and a table headed",
    ' * "used" would assert exactly that.',
    " */",
    "function renderRules(rules) {",
    "  const out = [];",
    '  out.push("## Rule relevance", "");',
    "  out.push(",
    '    "A rule is not invocable: no hook can say whether an agent read one.",',
    '    "What follows is RELEVANCE — did the scope of the rule meet a path a",',
    '    "session touched — and never usage.",',
    '    "",',
    "  );",
    "  if (rules.length === 0) {",
    '    out.push("No rule installed.", "");',
    "    return out;",
    "  }",
    "  out.push(",
    '    "| Rule | Scope | Matches | Sessions | Last relevant | Verdict | Cost |",',
    '    "| --- | --- | --- | --- | --- | --- | --- |",',
    "  );",
    "  for (const rule of rules) {",
    "    out.push(",
    '      "| " + rule.file + " | " +',
    '        (rule.globs.length === 0 ? "none" : "`" + rule.globs.join("`, `") + "`") +',
    '        " | " + rule.matches + " | " + rule.sessions + " | " +',
    '        (rule.lastSeen === null ? "never" : rule.lastSeen.slice(0, 10)) +',
    '        " | " + verdict(rule) + " | " + ruleCost(rule) + " |",',
    "    );",
    "  }",
    '  out.push("");',
    "  return out;",
    "}",
    "",
    "/**",
    " * A rule carries its moment of payment with its cost: an unscoped rule is",
    " * paid at every session, a scoped one only when it is relevant. Printing a",
    ' * bare "~0 tokens" for the second made a real cost look like none.',
    " */",
    "function ruleCost(rule) {",
    "  if (rule.perSession === null) return tokens(null);",
    '  if (rule.perSession > 0) return tokens(rule.perSession) + " every session";',
    '  return tokens(rule.perInvocation) + " when relevant";',
    "}",
    "",
    "function verdict(rule) {",
    '  if (rule.bucket === "cannot-say") return "cannot say (no scope)";',
    '  if (rule.bucket === "relevant") return "relevant";',
    '  return "never relevant";',
    "}",
    "",
    "/**",
    " * The section that must never be cut. Everything here is a reason not to",
    " * read the tables above as more than they are.",
    " */",
    "function renderLimits(report) {",
    "  const limits = report.limits;",
    "  const out = [];",
    '  out.push("## What this measure cannot say", "");',
    "  out.push(",
    '    "- **Rules are not observable.** Relevance is not reading: a rule whose",',
    '    "  scope was met may never have been read, and one that was read leaves",',
    '    "  no trace either way.",',
    "  );",
    "  const unscoped = report.rules.filter((rule) => rule.globs.length === 0);",
    "  if (unscoped.length > 0) {",
    "    out.push(",
    '      "- **" + unscoped.length + " rule(s) declare no `paths:` scope**: there is",',
    '      "  no scope to meet, so nothing can be said about them either way — and",',
    '      "  they are paid at every session: " +',
    '        unscoped.map((rule) => rule.file).join(", ") + ".",',
    "    );",
    "  }",
    "  out.push(",
    '    "- **An invocation is not a benefit.** The journal says a skill ran, never",',
    '    "  that it helped.",',
    '    "- **A harness whose hooks are not installed leaves no trace.** Sessions",',
    '    "  run there are invisible here, and look like an absence of work.",',
    "  );",
    "  if (limits.unnamedDelegations > 0) {",
    "    out.push(",
    '      "- **" + limits.unnamedDelegations + " delegation(s) out of " +',
    '        limits.delegations + " carry no agent name**: the payload keys were not",',
    '      "  recognised, so sub-agent counts are unreliable. Do not read a zero",',
    '      "  there as never delegated to.",',
    "    );",
    "  }",
    "  if (limits.toolCallsWithoutPath > 0) {",
    "    out.push(",
    '      "- **" + limits.toolCallsWithoutPath + " tool call(s) out of " +',
    '        limits.toolCalls + " carry no path**: excluded by configuration,",',
    '      "  outside the repo, or a tool that touches no file. A rule scoped to an",',
    '      "  excluded path can never appear relevant.",',
    "    );",
    "  }",
    "  if (limits.excludeGlobs.length > 0) {",
    "    out.push(",
    '      "- **Paths matching `" + limits.excludeGlobs.join("`, `") +',
    '        "` are journalled as null** by configuration.",',
    "    );",
    "  }",
    "  if (!limits.collectionEnabled) {",
    "    out.push(",
    '      "- **Collection is currently disabled** (`[usage] enabled = false`): the",',
    '      "  window ends whenever it was switched off.",',
    "    );",
    "  }",
    "  out.push(",
    '    "- **The journal holds " + limits.retentionDays + " days.** Anything older was",',
    '    "  pruned: this is a window, not a history.",',
    "  );",
    '  if (limits.cost === "not-measured") {',
    "    out.push(",
    '      "- **The cost was not measured.** Run `agentsdir doctor --json` and pass",',
    '      "  it with `--doctor` to cross usage with cost. An unmeasured cost is not",',
    '      "  a zero cost.",',
    "    );",
    "  }",
    '  out.push("");',
    "  return out;",
    "}",
    "",
  ];
}
