import type { PackContent } from "./index.js";

/**
 * Pack `verification`: a harness-agnostic `$verify` skill (proof matrix,
 * PASS / NOT PROVEN / BLOCKED verdicts, standalone HTML report) and its rule.
 * Transposed from the source model without its product-specific ties: the
 * report script is dependency-free Node, paths resolve from the repo root,
 * and nothing here references a file absent from the target repo.
 */
export function verificationPack(): PackContent {
  return {
    name: "verification",
    files: [
      { path: ".agents/skills/verify/SKILL.md", content: renderSkillMd() },
      {
        path: ".agents/skills/verify/references/proof-matrix.md",
        content: renderProofMatrixReference(),
      },
      {
        path: ".agents/skills/verify/scripts/build-report.mjs",
        content: renderBuildReportScript(),
      },
      { path: ".agents/rules/verification.md", content: renderRule() },
    ],
    skills: ["verify"],
    rules: ["verification.md"],
    keepExisting: [],
  };
}

function renderSkillMd(): string {
  return [
    "---",
    "name: verify",
    'description: "Proves a delivered change against its acceptance criteria, with commands and recorded evidence. Use when the user asks to verify, validate or prove a change, a task or a release."',
    "disable-model-invocation: true",
    'display-name: "Verify"',
    'short-description: "Proves a change against its acceptance criteria"',
    'color: "#1F7A3D"',
    "icon: badge-check",
    'default-prompt: "Use $verify to prove the delivered change against its acceptance criteria."',
    "implicit: false",
    "---",
    "",
    "# Verify",
    "",
    "## Objective",
    "",
    "Prove that a delivered change satisfies its acceptance criteria — with",
    "observed evidence, never with claims. The output is a proof matrix and a",
    "standalone HTML report; each criterion gets a verdict: PASS, NOT PROVEN or",
    "BLOCKED.",
    "",
    "## Procedure",
    "",
    "1. Collect the acceptance criteria of the change (task file, issue or PR",
    "   description). One row of the proof matrix per criterion — the format is",
    "   specified in references/proof-matrix.md.",
    "2. For each criterion, execute the observable step that proves it (a",
    "   command, a test run, an inspection), from the repository root.",
    "3. Record the evidence verbatim: command executed, relevant output, exit",
    "   code. Trim noise, never trim the part that carries the proof.",
    "4. Assign the verdict: PASS (the evidence shows the criterion holds),",
    "   NOT PROVEN (no observable evidence either way), BLOCKED (the proving",
    "   step cannot run — missing tool or access). Never guess: a missing proof",
    "   is NOT PROVEN, not PASS.",
    "5. Write the matrix as JSON and build the report:",
    "   `node .agents/skills/verify/scripts/build-report.mjs <matrix.json> <report.html>`",
    "   (for example into `.agents/output/`, which stays out of git).",
    "6. Deliver the verdict summary first, then the report path.",
    "",
    "## Verification",
    "",
    "- The report file exists and opens as a single self-contained HTML page.",
    "- Every criterion of the source change appears in the matrix with a",
    "  verdict and its evidence; no PASS stands without a quoted observation.",
    "",
  ].join("\n");
}

function renderProofMatrixReference(): string {
  return [
    "# Proof matrix format",
    "",
    "The proof matrix is the single artifact of a verification: one row per",
    "acceptance criterion, each row carrying the observed step and the evidence",
    "it produced. It is written as JSON and rendered to HTML by",
    "`scripts/build-report.mjs`.",
    "",
    "## JSON shape",
    "",
    "```json",
    "{",
    '  "title": "Task 42 — payment retries",',
    '  "criteria": [',
    "    {",
    '      "criterion": "Retries stop after three attempts",',
    '      "step": "npm test -- retries",',
    '      "evidence": "3 tests passed; log shows attempts 1..3 then giving up",',
    '      "verdict": "PASS"',
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "## Verdicts",
    "",
    "| Verdict | Meaning |",
    "| --- | --- |",
    "| PASS | The recorded evidence shows the criterion holds |",
    "| NOT PROVEN | No observable evidence either way — say so, never guess |",
    "| BLOCKED | The proving step cannot run (missing tool, missing access) |",
    "",
    "## Rules of evidence",
    "",
    "- Evidence is an observation (command output, exit code, file content),",
    "  never a restatement of the claim.",
    "- One criterion per row — a row proving two things proves neither.",
    "- The overall verdict of a verification is PASS only when every row is",
    "  PASS.",
    "",
  ].join("\n");
}

function renderBuildReportScript(): string {
  return [
    "#!/usr/bin/env node",
    "// Standalone proof-matrix report builder — Node only, zero dependencies.",
    "// Usage (from the repository root):",
    "//   node .agents/skills/verify/scripts/build-report.mjs <matrix.json> <report.html>",
    "// The matrix format is specified in ../references/proof-matrix.md.",
    "",
    'import { mkdirSync, readFileSync, writeFileSync } from "node:fs";',
    'import { dirname } from "node:path";',
    "",
    "const [matrixPath, reportPath] = process.argv.slice(2);",
    "if (matrixPath === undefined || reportPath === undefined) {",
    '  console.error("Usage: node build-report.mjs <matrix.json> <report.html>");',
    "  process.exit(2);",
    "}",
    "",
    'const matrix = JSON.parse(readFileSync(matrixPath, "utf8"));',
    "const title =",
    '  typeof matrix.title === "string" && matrix.title !== ""',
    "    ? matrix.title",
    '    : "Verification report";',
    "const criteria = Array.isArray(matrix.criteria) ? matrix.criteria : [];",
    "if (criteria.length === 0) {",
    '  console.error("The matrix has no criteria — nothing to report.");',
    "  process.exit(2);",
    "}",
    "",
    'const VERDICTS = new Set(["PASS", "NOT PROVEN", "BLOCKED"]);',
    "const rows = criteria.map((row, index) => {",
    '  const verdict = VERDICTS.has(row.verdict) ? row.verdict : "NOT PROVEN";',
    '  const slug = verdict.toLowerCase().replace(" ", "-");',
    "  return [",
    '    `    <tr class="${slug}">`,',
    "    `      <td>${index + 1}</td>`,",
    "    `      <td>${esc(row.criterion)}</td>`,",
    "    `      <td><code>${esc(row.step)}</code></td>`,",
    "    `      <td><pre>${esc(row.evidence)}</pre></td>`,",
    '    `      <td class="verdict">${verdict}</td>`,',
    "    `    </tr>`,",
    '  ].join("\\n");',
    "});",
    "const count = (verdict) =>",
    "  criteria.filter(",
    '    (row) => (VERDICTS.has(row.verdict) ? row.verdict : "NOT PROVEN") === verdict,',
    "  ).length;",
    'const overall = count("PASS") === criteria.length ? "PASS" : "NOT PROVEN";',
    "",
    "const html = [",
    '  "<!doctype html>",',
    '  "<html lang=\\"en\\">",',
    '  "<head>",',
    '  "<meta charset=\\"utf-8\\">",',
    "  `<title>${esc(title)}</title>`,",
    '  "<style>",',
    '  "body { font: 14px/1.5 system-ui, sans-serif; margin: 2rem; color: #1a1a1a; }",',
    '  "table { border-collapse: collapse; width: 100%; }",',
    '  "th, td { border: 1px solid #ccc; padding: 0.5rem; text-align: left; vertical-align: top; }",',
    '  "pre { margin: 0; white-space: pre-wrap; }",',
    '  ".pass .verdict { color: #1f7a3d; font-weight: bold; }",',
    '  ".not-proven .verdict { color: #b45309; font-weight: bold; }",',
    '  ".blocked .verdict { color: #b91c1c; font-weight: bold; }",',
    '  "</style>",',
    '  "</head>",',
    '  "<body>",',
    "  `<h1>${esc(title)}</h1>`,",
    '  `<p>Overall: <strong>${overall}</strong> — ${count("PASS")} PASS, ${count(',
    '    "NOT PROVEN",',
    '  )} NOT PROVEN, ${count("BLOCKED")} BLOCKED.</p>`,',
    '  "<table>",',
    '  "  <thead>",',
    '  "    <tr><th>#</th><th>Criterion</th><th>Observed step</th><th>Evidence</th><th>Verdict</th></tr>",',
    '  "  </thead>",',
    '  "  <tbody>",',
    '  rows.join("\\n"),',
    '  "  </tbody>",',
    '  "</table>",',
    '  "</body>",',
    '  "</html>",',
    '  "",',
    '].join("\\n");',
    "",
    "mkdirSync(dirname(reportPath), { recursive: true });",
    "writeFileSync(reportPath, html);",
    "console.log(`Report written: ${reportPath} (overall ${overall})`);",
    "",
    "function esc(value) {",
    '  return String(value ?? "")',
    '    .replaceAll("&", "&amp;")',
    '    .replaceAll("<", "&lt;")',
    '    .replaceAll(">", "&gt;")',
    '    .replaceAll(\'"\', "&quot;");',
    "}",
    "",
  ].join("\n");
}

function renderRule(): string {
  return [
    "# Verification",
    "",
    "Read before declaring any task, fix or release done.",
    "",
    "## Rules",
    "",
    "- ALWAYS verify against the acceptance criteria of the change, not against",
    "  what the code looks like.",
    "- ALWAYS record the evidence next to the verdict: command executed,",
    "  relevant output, exit code.",
    "- NEVER report PASS without observed evidence — an unproven criterion is",
    "  NOT PROVEN, and a step that cannot run is BLOCKED.",
    "- Use the `$verify` skill to build the proof matrix and its HTML report.",
    "",
    "## Examples",
    "",
    "GOOD:",
    "",
    "```",
    'Criterion: build passes — step: "npm run build" — evidence: exited 0,',
    '"Build success in 2.1s". Verdict: PASS',
    "```",
    "",
    "BAD:",
    "",
    "```",
    "Criterion: build passes — evidence: the code looks correct. Verdict: PASS",
    "```",
    "",
    "## Verdicts",
    "",
    "| Verdict | When |",
    "| --- | --- |",
    "| PASS | The recorded evidence shows the criterion holds |",
    "| NOT PROVEN | No observable evidence either way — say so, never guess |",
    "| BLOCKED | The proving step cannot run (missing tool, missing access) |",
    "",
  ].join("\n");
}
