import type { PackContent } from "./index.js";

/**
 * Pack `worktrees`: git worktree lifecycle scripts shared by every harness,
 * rewritten in portable Node (the source model was Unix-only: bash, perl,
 * lsof, trash). Guard rails kept: refuse the main working copy (explicit env
 * override), transient files always removed, never a brutal recursive
 * deletion. `.codex/environments/environment.toml` is deliberately NOT
 * generated (not corroborated by public Codex docs — see docs/harness.md);
 * the pack rule explains the Codex UI wiring instead.
 */
export function worktreesPack(): PackContent {
  return {
    name: "worktrees",
    files: [
      {
        path: ".agents/scripts/worktrees/worktree-context.mjs",
        content: renderContextScript(),
      },
      {
        path: ".agents/scripts/worktrees/worktree-setup.mjs",
        content: renderSetupScript(),
      },
      {
        path: ".agents/scripts/worktrees/worktree-cleanup.mjs",
        content: renderCleanupScript(),
      },
      { path: ".agents/rules/worktrees.md", content: renderRule() },
      { path: ".cursor/worktrees.json", content: renderCursorWorktreesJson() },
    ],
    skills: [],
    rules: ["worktrees.md"],
    keepExisting: [".cursor/worktrees.json"],
  };
}

/** `.cursor/worktrees.json` — platform keys, paths relative to `.cursor/`. */
function renderCursorWorktreesJson(): string {
  const setup = "node ../.agents/scripts/worktrees/worktree-setup.mjs";
  const cleanup = "node ../.agents/scripts/worktrees/worktree-cleanup.mjs";
  return `${JSON.stringify(
    {
      "setup-worktree-unix": setup,
      "setup-worktree-windows": setup,
      "cleanup-worktree-unix": cleanup,
      "cleanup-worktree-windows": cleanup,
    },
    null,
    2,
  )}\n`;
}

function renderContextScript(): string {
  return [
    "#!/usr/bin/env node",
    "// Worktree context resolution — shared library of the agentsdir worktrees",
    "// pack. Node only, zero dependencies. Run it directly to print the resolved",
    "// context as JSON.",
    "//",
    "// Resolution chains (no machine path is ever hard-coded):",
    "//   worktree path  CODEX_WORKTREE_PATH, then CONDUCTOR_WORKSPACE_PATH, then",
    "//                  CURSOR_WORKTREE_PATH, then the current directory;",
    "//   main copy      git itself (rev-parse --git-common-dir) — an environment",
    "//                  variable cannot lie about which copy is the main one;",
    "//   project name   [project] name of .agents.toml, then the main copy folder;",
    "//   ports          a deterministic block of 10 derived from the worktree name.",
    "",
    'import { execFileSync, spawnSync } from "node:child_process";',
    'import { readFileSync } from "node:fs";',
    'import { basename, dirname, join, resolve } from "node:path";',
    'import { fileURLToPath } from "node:url";',
    "",
    "export function resolveContext(env = process.env, cwd = process.cwd()) {",
    "  const worktreePath = resolve(",
    "    env.CODEX_WORKTREE_PATH ||",
    "      env.CONDUCTOR_WORKSPACE_PATH ||",
    "      env.CURSOR_WORKTREE_PATH ||",
    "      cwd,",
    "  );",
    "  let commonDir;",
    "  try {",
    "    commonDir = execFileSync(",
    '      "git",',
    '      ["-C", worktreePath, "rev-parse", "--git-common-dir"],',
    '      { encoding: "utf8" },',
    "    ).trim();",
    "  } catch {",
    "    throw new Error(",
    "      `Not inside a git repository (resolved worktree path: ${worktreePath}).`,",
    "    );",
    "  }",
    "  const mainPath = dirname(resolve(worktreePath, commonDir));",
    "  const worktreeName = basename(worktreePath);",
    '  const manifest = readManifestSubset(join(mainPath, ".agents.toml"));',
    "  return {",
    "    worktreePath,",
    "    mainPath,",
    "    isMain: samePath(worktreePath, mainPath),",
    "    worktreeName,",
    "    projectName: manifest.projectName || basename(mainPath),",
    "    portBase: 3000 + (hashName(worktreeName) % 1000) * 10,",
    "    setupCommands: manifest.setup,",
    "    cleanupCommands: manifest.cleanup,",
    "  };",
    "}",
    "",
    "/** Exit 2 in the main working copy unless AGENTSDIR_ALLOW_MAIN=1. */",
    "export function guardAgainstMainCopy(context) {",
    '  if (!context.isMain || process.env.AGENTSDIR_ALLOW_MAIN === "1") {',
    "    return;",
    "  }",
    "  console.error(",
    "    `Refusing to run in the main working copy (${context.mainPath}).` +",
    '      " Set AGENTSDIR_ALLOW_MAIN=1 to override explicitly.",',
    "  );",
    "  process.exit(2);",
    "}",
    "",
    "/** Runs declared commands in order through the system shell; false on first failure. */",
    "export function runCommands(label, commands, cwd) {",
    "  for (const command of commands) {",
    "    console.log(`${label}: ${command}`);",
    '    const run = spawnSync(command, { shell: true, stdio: "inherit", cwd });',
    "    if (run.status !== 0) {",
    "      console.error(",
    '        `${label}: \\"${command}\\" exited with ${run.status ?? "a signal"}.`,',
    "      );",
    "      return false;",
    "    }",
    "  }",
    "  return true;",
    "}",
    "",
    "// Minimal reader of the CLI-rendered .agents.toml (single-line values,",
    "// double-quoted strings) — just enough for [project] name and [worktrees].",
    "function readManifestSubset(path) {",
    '  const result = { projectName: "", setup: [], cleanup: [] };',
    "  let raw;",
    "  try {",
    '    raw = readFileSync(path, "utf8");',
    "  } catch {",
    "    return result;",
    "  }",
    '  let section = "";',
    '  for (const line of raw.split("\\n")) {',
    "    const trimmed = line.trim();",
    '    if (trimmed.startsWith("[")) {',
    "      section = trimmed;",
    "      continue;",
    "    }",
    "    const match = trimmed.match(/^([A-Za-z-]+)\\s*=\\s*(.+)$/);",
    "    if (match === null) {",
    "      continue;",
    "    }",
    '    if (section === "[project]" && match[1] === "name") {',
    '      result.projectName = parseStrings(match[2])[0] ?? "";',
    '    } else if (section === "[worktrees]" && match[1] === "setup") {',
    "      result.setup = parseStrings(match[2]);",
    '    } else if (section === "[worktrees]" && match[1] === "cleanup") {',
    "      result.cleanup = parseStrings(match[2]);",
    "    }",
    "  }",
    "  return result;",
    "}",
    "",
    "function parseStrings(value) {",
    '  const tokens = value.match(/"(?:[^"\\\\]|\\\\.)*"/g) ?? [];',
    "  return tokens.map((token) => JSON.parse(token));",
    "}",
    "",
    "function samePath(a, b) {",
    '  return process.platform === "win32"',
    "    ? a.toLowerCase() === b.toLowerCase()",
    "    : a === b;",
    "}",
    "",
    "function hashName(name) {",
    "  let hash = 0;",
    "  for (const char of name) {",
    "    hash = (hash * 31 + char.codePointAt(0)) >>> 0;",
    "  }",
    "  return hash;",
    "}",
    "",
    "if (",
    "  process.argv[1] !== undefined &&",
    "  samePath(resolve(process.argv[1]), fileURLToPath(import.meta.url))",
    ") {",
    "  console.log(JSON.stringify(resolveContext(), null, 2));",
    "}",
    "",
  ].join("\n");
}

function renderSetupScript(): string {
  return [
    "#!/usr/bin/env node",
    "// Worktree setup — run it inside a fresh git worktree:",
    "//   node .agents/scripts/worktrees/worktree-setup.mjs",
    "// Refuses the main working copy (AGENTSDIR_ALLOW_MAIN=1 overrides). Writes",
    "// the resolved context for the session's tools, then runs the commands",
    "// declared under [worktrees] setup in .agents.toml, in order. All",
    "// orchestration is Node; declared commands run through the system shell.",
    "",
    'import { mkdirSync, renameSync, rmSync, writeFileSync } from "node:fs";',
    'import { join } from "node:path";',
    "import {",
    "  guardAgainstMainCopy,",
    "  resolveContext,",
    "  runCommands,",
    '} from "./worktree-context.mjs";',
    "",
    "const context = resolveContext();",
    "guardAgainstMainCopy(context);",
    'const outputDir = join(context.worktreePath, ".agents", "output");',
    'const contextFile = join(outputDir, "worktree-context.json");',
    "const transient = `${contextFile}.tmp`;",
    "let ok = false;",
    "try {",
    "  // atomic write: the durable context lands in a single rename",
    "  mkdirSync(outputDir, { recursive: true });",
    "  writeFileSync(transient, `${JSON.stringify(context, null, 2)}\\n`);",
    "  renameSync(transient, contextFile);",
    "  ok = runCommands(",
    '    "worktree-setup",',
    "    context.setupCommands,",
    "    context.worktreePath,",
    "  );",
    "} finally {",
    "  // the transient file never survives, success or failure",
    "  rmSync(transient, { force: true });",
    "}",
    "if (ok) {",
    "  console.log(",
    "    `worktree-setup: ready — ${context.worktreeName} (ports ${context.portBase}-${context.portBase + 9}).`,",
    "  );",
    "}",
    "process.exit(ok ? 0 : 1);",
    "",
  ].join("\n");
}

function renderCleanupScript(): string {
  return [
    "#!/usr/bin/env node",
    "// Worktree cleanup — run it inside the worktree being retired:",
    "//   node .agents/scripts/worktrees/worktree-cleanup.mjs",
    "// Refuses the main working copy (AGENTSDIR_ALLOW_MAIN=1 overrides). Runs",
    "// the commands declared under [worktrees] cleanup in .agents.toml, then",
    "// removes the transient context file this pack owns. It NEVER deletes the",
    "// worktree itself: retiring it stays an explicit git command, printed last.",
    "",
    'import { rmSync } from "node:fs";',
    'import { join } from "node:path";',
    "import {",
    "  guardAgainstMainCopy,",
    "  resolveContext,",
    "  runCommands,",
    '} from "./worktree-context.mjs";',
    "",
    "const context = resolveContext();",
    "guardAgainstMainCopy(context);",
    "let ok = false;",
    "try {",
    "  ok = runCommands(",
    '    "worktree-cleanup",',
    "    context.cleanupCommands,",
    "    context.worktreePath,",
    "  );",
    "} finally {",
    "  // owned transient state goes away even when a cleanup command fails",
    "  rmSync(",
    '    join(context.worktreePath, ".agents", "output", "worktree-context.json"),',
    "    { force: true },",
    "  );",
    "}",
    "console.log(",
    '  "worktree-cleanup: done. To retire the worktree itself, run from the main copy:",',
    ");",
    "console.log(`  git worktree remove ${JSON.stringify(context.worktreePath)}`);",
    "process.exit(ok ? 0 : 1);",
    "",
  ].join("\n");
}

function renderRule(): string {
  return [
    "# Worktrees",
    "",
    "Read before creating, setting up or retiring a git worktree of this repo.",
    "",
    "## Rules",
    "",
    "- ALWAYS run the setup script right after creating a worktree, from inside",
    "  it: `node .agents/scripts/worktrees/worktree-setup.mjs`.",
    "- ALWAYS run the cleanup script before retiring a worktree:",
    "  `node .agents/scripts/worktrees/worktree-cleanup.mjs` — it never deletes",
    "  the worktree itself; it prints the exact `git worktree remove` command to",
    "  run from the main copy.",
    "- NEVER run setup or cleanup in the main working copy: they refuse. Set",
    "  AGENTSDIR_ALLOW_MAIN=1 to override explicitly — and know why you do it.",
    "- Declare stack-specific steps (dependency install, environment cloning) in",
    "  `.agents.toml`, never inside the scripts — the pack stays",
    "  language-agnostic.",
    "",
    "## Extension points",
    "",
    "Single-line commands, run in order through the system shell, from the",
    "worktree root; the run stops at the first failure:",
    "",
    "```toml",
    "[worktrees]",
    'setup = ["npm ci"]',
    "cleanup = []",
    "```",
    "",
    "## What the scripts resolve",
    "",
    "`worktree-context.mjs` prints the resolved context as JSON: the worktree",
    "path (CODEX_WORKTREE_PATH, then CONDUCTOR_WORKSPACE_PATH, then",
    "CURSOR_WORKTREE_PATH, then the current directory), the main copy (resolved",
    "by git itself, never by an environment variable), the project name (the",
    "manifest, then the main folder name) and a deterministic block of 10 ports",
    "per worktree.",
    "",
    "## Harness wiring",
    "",
    "| Harness | Wiring |",
    "| --- | --- |",
    "| Cursor | `.cursor/worktrees.json` (installed by this pack) runs setup and cleanup through its platform keys |",
    "| Codex | declare `node .agents/scripts/worktrees/worktree-setup.mjs` as the setup command in the Codex cloud environment UI — `.codex/environments/environment.toml` is not publicly documented and is never generated |",
    "| Claude Code, terminal | run the two commands above by hand at worktree creation and retirement |",
    "",
  ].join("\n");
}
