import { entryExists, resolveInsideRepo, writeFileAtomic } from "./fs-utils.js";
import { createHash } from "node:crypto";
import {
  lstat,
  mkdir,
  readdir,
  readFile,
  readlink,
  rm,
  symlink,
  unlink,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { EXIT_CODES } from "../exit-codes.js";
import { detectGitSymlinks } from "./detect.js";
import { CliError } from "./errors.js";
import { frontmatterBlockLength } from "./frontmatter.js";
import type { ProjectionMode } from "./manifest.js";

export const GENERATED_HEADER =
  "GENERATED by agentsdir — edit the source in .agents/ and run `agentsdir sync`.";

const MD_HEADER_LINE = `<!-- ${GENERATED_HEADER} -->`;

/**
 * Copy-mode CLAUDE.md is a bridge, not a copy: Claude Code reads AGENTS.md
 * through the `@AGENTS.md` import, so there is a single source either way.
 */
export const CLAUDE_MD_COPY = `@AGENTS.md\n\n${MD_HEADER_LINE}\n`;

export interface ProjectionSpec {
  /** Repo-relative target, POSIX. */
  target: string;
  /** Repo-relative source, POSIX. */
  source: string;
  kind: "file" | "dir";
}

/** Claude Code projections: the CLAUDE.md bridge and three directory mirrors. */
export const CLAUDE_PROJECTIONS: readonly ProjectionSpec[] = [
  { target: "CLAUDE.md", source: "AGENTS.md", kind: "file" },
  { target: ".claude/rules", source: ".agents/rules", kind: "dir" },
  { target: ".claude/skills", source: ".agents/skills", kind: "dir" },
  { target: ".claude/agents", source: ".agents/agents", kind: "dir" },
];

/**
 * Whether a repo-relative path is a projection or lives inside one — the filter
 * the symlink-health invariant applies to what git reports, so the answer stays
 * derived from the specs above instead of a second hard-coded list.
 */
export function isProjectionPath(path: string): boolean {
  return CLAUDE_PROJECTIONS.some(
    (spec) => path === spec.target || path.startsWith(`${spec.target}/`),
  );
}

export interface ProjectOptions {
  /** Comes from the manifest — never recomputed silently. */
  mode: ProjectionMode;
  dryRun?: boolean;
  /** Copy mode: fingerprints recorded by the previous run, to recognize our stale copies. */
  previousHashes?: Record<string, string>;
  /**
   * Copy mode: would-be content of source files (repo-relative POSIX paths),
   * so a dry run computes the same plan as a run that writes those sources
   * first (`sync` regenerates Codex artifacts before projecting them).
   */
  overlay?: Record<string, Buffer>;
  /**
   * Projections `unproject` is about to remove, subtracted from the real disk
   * when classifying. This is what lets the whole plan — foreign targets
   * included — be computed before the first deletion. It replaces a blanket
   * "assume absent": that one short-circuited the classification entirely, so
   * no foreign target could ever be reported on a mode switch, in a dry run or
   * anywhere else.
   */
  pendingRemovals?: readonly string[];
}

export interface ProjectionChange {
  path: string;
  action: "link" | "write" | "unchanged";
  /** False when the target did not exist before this run (created vs updated). */
  existed: boolean;
}

export interface ProjectionResult {
  changes: ProjectionChange[];
  /** Copy mode: sha256 fingerprint of every generated file, for [projections.hashes]. */
  hashes: Record<string, string>;
}

/** Materializes the projections. Never overwrites a file it does not own (exit 1). */
export async function project(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  return options.mode === "symlink"
    ? projectSymlinks(root, options)
    : projectCopies(root, options);
}

export interface RefreshOptions {
  /** Mode to project into — the one the manifest will record. */
  mode: ProjectionMode;
  /** Mode currently recorded; when it differs from `mode`, this is a switch. */
  previousMode: ProjectionMode;
  /** Fingerprints recorded by the previous run. */
  previousHashes: Record<string, string>;
  /** Would-be content of source files about to be written (repo-relative POSIX). */
  overlay?: Record<string, Buffer>;
  dryRun?: boolean;
}

export interface RefreshResult extends ProjectionResult {
  /** Projections removed before this run projected: stale mode, or orphans. */
  removed: string[];
}

/**
 * Brings the projections back in line with the source of truth: first removes
 * what must not survive — the previous mode's projections on a switch, the
 * copies whose source is gone otherwise — then projects. `sync` and the
 * generators share this single orchestration; the caller stays responsible for
 * recording the returned fingerprints in the manifest.
 */
export async function refreshProjections(
  root: string,
  options: RefreshOptions,
): Promise<RefreshResult> {
  const switching = options.mode !== options.previousMode;
  const remove = async (dryRun: boolean): Promise<{ removed: string[] }> =>
    switching
      ? await unproject(root, {
          mode: options.previousMode,
          dryRun,
          previousHashes: options.previousHashes,
        })
      : await removeOrphanProjections(root, {
          mode: options.mode,
          hashes: options.previousHashes,
          dryRun,
        });
  // what the removal would take, computed without taking it
  const { removed } = await remove(true);
  const plan: ProjectOptions = {
    mode: options.mode,
    // on a switch the recorded fingerprints describe the mode being left
    previousHashes: switching ? {} : options.previousHashes,
    ...(options.overlay === undefined ? {} : { overlay: options.overlay }),
    pendingRemovals: removed,
  };
  // The whole plan, classified against the real disk minus that removal. A
  // foreign target throws here — before a single copy is deleted. It used to
  // throw after, leaving a repository half in each mode, with a manifest still
  // announcing the mode it had left and no command able to describe it.
  const projection = await planProjection(root, plan, options);
  if (options.dryRun === true) {
    return { ...projection, removed };
  }
  await remove(false);
  // the removal happened: the disk now is the clean slate the plan assumed
  await project(root, { ...plan, pendingRemovals: [] });
  return { ...projection, removed };
}

/** The plan, with the guarantee the caller cares about stated in the failure. */
async function planProjection(
  root: string,
  plan: ProjectOptions,
  options: RefreshOptions,
): Promise<ProjectionResult> {
  try {
    return await project(root, { ...plan, dryRun: true });
  } catch (error) {
    if (options.mode === options.previousMode || !(error instanceof CliError)) {
      throw error;
    }
    throw new CliError(
      `${error.message}\nThe switch to ${options.mode} mode was aborted before anything was removed: the repository is untouched, still in ${options.previousMode} mode.`,
      error.exitCode,
    );
  }
}

export interface UnprojectOptions {
  /** Mode whose projections are being removed — the one leaving the manifest. */
  mode: ProjectionMode;
  dryRun?: boolean;
  /** Copy mode: fingerprints recorded by the previous run, to recognize our copies. */
  previousHashes?: Record<string, string>;
}

/**
 * Removes the projections of `mode` before the other mode is materialized.
 * Only what agentsdir owns is deleted — a correct link, or a copy matching its
 * recorded fingerprint or carrying the generated header. Anything else is left
 * on disk, where projecting the new mode reports it as a foreign target.
 */
export async function unproject(
  root: string,
  options: UnprojectOptions,
): Promise<{ removed: string[] }> {
  const removed =
    options.mode === "symlink"
      ? await ownedSymlinks(root)
      : await ownedCopies(root, options.previousHashes ?? {});
  if (!options.dryRun) {
    for (const path of removed) {
      await rm(toAbsolute(root, path), { force: true });
    }
    // the mirrors are ours; leftover entries keep the directory
    for (const spec of CLAUDE_PROJECTIONS) {
      if (spec.kind === "dir") {
        await removeIfNoFilesLeft(root, spec.target);
      }
    }
  }
  return { removed };
}

async function ownedSymlinks(root: string): Promise<string[]> {
  const owned: string[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const state = await classifyLinkTarget(
      toAbsolute(root, spec.target),
      relativeLinkTarget(spec),
    );
    if (state === "correct") {
      owned.push(spec.target);
    }
  }
  return owned;
}

async function ownedCopies(
  root: string,
  previousHashes: Record<string, string>,
): Promise<string[]> {
  const candidates = new Set<string>(Object.keys(previousHashes));
  candidates.add("CLAUDE.md");
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    for (const file of await walkFiles(
      toAbsolute(root, spec.target),
      spec.target,
    )) {
      candidates.add(file.rel);
    }
  }
  const owned: string[] = [];
  for (const path of [...candidates].sort()) {
    let current: Buffer;
    try {
      current = await readFile(toAbsolute(root, path));
    } catch {
      continue;
    }
    const ours =
      previousHashes[path] === sha256(current) ||
      (path.endsWith(".md") &&
        current.toString("utf8").includes(GENERATED_HEADER));
    if (ours) {
      owned.push(path);
    }
  }
  return owned;
}

/**
 * Copies left behind by a deleted source (a rule removed from `.agents/rules/`
 * keeps its `.claude/rules/` mirror otherwise). Symlink mode has none: its four
 * targets are fixed and always point at a live source.
 */
export async function removeOrphanProjections(
  root: string,
  options: {
    mode: ProjectionMode;
    hashes: Record<string, string>;
    dryRun?: boolean;
  },
): Promise<{ removed: string[] }> {
  if (options.mode === "symlink") {
    return { removed: [] };
  }
  const expected = new Set(
    (await expectedCopies(root, {})).map((file) => file.path),
  );
  const removed: string[] = [];
  for (const path of Object.keys(options.hashes).sort()) {
    if (expected.has(path) || !(await entryExists(toAbsolute(root, path)))) {
      continue;
    }
    removed.push(path);
  }
  // and the ones no fingerprint ever recorded. `check` reports them, so `sync`
  // has to be able to remove them — otherwise check says "run sync" and sync
  // leaves the file in place, which is a deadlock, not a repair.
  const alreadyListed = new Set(removed);
  for (const path of await projectedFiles(root)) {
    if (expected.has(path) || alreadyListed.has(path)) {
      continue;
    }
    removed.push(path);
  }
  removed.sort();
  if (!options.dryRun) {
    for (const path of removed) {
      await rm(toAbsolute(root, path), { force: true });
    }
    for (const spec of CLAUDE_PROJECTIONS) {
      if (spec.kind === "dir") {
        await removeIfNoFilesLeft(root, spec.target);
      }
    }
  }
  return { removed };
}

/**
 * Removes a projection directory once it holds no file at all, at any depth.
 * A non-recursive readdir was not enough: a projected skill has `agents/` and
 * `assets/` subfolders, so the parent survived as a real directory holding only
 * empty ones — enough to make the next mode switch classify it as foreign and
 * throw. `pack.ts` had the same defect and the same fix; this reuses the walk
 * already in this module rather than open-coding a second traversal.
 */
async function removeIfNoFilesLeft(root: string, path: string): Promise<void> {
  const abs = toAbsolute(root, path);
  try {
    // the shared walk decides: no file at any depth, and the directory goes —
    // which is what makes a mode switch find a clean slate instead of a shell
    // of empty folders it would classify as a foreign target
    if ((await walkFiles(abs, path)).length === 0) {
      await rm(abs, { recursive: true, force: true });
      return;
    }
    // files remain, so the mirror stays; its emptied subfolders still go, or a
    // removed skill would leave its `agents/` and `assets/` behind for good
    for (const entry of await readdir(abs, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        await removeIfNoFilesLeft(root, `${path}/${entry.name}`);
      }
    }
  } catch {
    // unreadable, or raced with something else: cleaning up is best effort and
    // never a failure of its own — the directory simply stays
  }
}

/**
 * Will this target be gone by the time the projection is written? The plan is
 * computed before the first deletion, so classifying the disk means subtracting
 * what `unproject` is about to remove. Two shapes, because the two directions
 * of a switch remove different things:
 *
 * - symlink to copy: `unproject` returns `.claude/rules`, the link itself, and
 *   the copies to plan are files *under* it — so an ancestor counts. Without
 *   this, `readFile` would follow the still-standing link into the source and
 *   report every copy as a foreign target.
 * - copy to symlink: `unproject` returns individual files, and the directory
 *   goes away only once every file under it is removed. A survivor keeps it
 *   standing, which is exactly the foreign target a real run would hit.
 */
async function willBeRemoved(
  root: string,
  target: string,
  kind: "file" | "dir",
  pending: ReadonlySet<string>,
): Promise<boolean> {
  if (pending.size === 0) {
    return false;
  }
  const parts = target.split("/");
  for (let depth = parts.length; depth >= 1; depth -= 1) {
    if (pending.has(parts.slice(0, depth).join("/"))) {
      return true;
    }
  }
  if (kind !== "dir") {
    return false;
  }
  const files = await walkFiles(toAbsolute(root, target), target);
  return files.length > 0 && files.every((file) => pending.has(file.rel));
}

export interface VerifyOptions {
  mode: ProjectionMode;
  /** Copy mode: fingerprints recorded in the manifest. */
  hashes: Record<string, string>;
}

export type DriftKind =
  | "missing"
  | "modified"
  | "replaced-by-copy"
  | "header-removed"
  | "stale"
  | "orphan";

export interface ProjectionDrift {
  path: string;
  kind: DriftKind;
  detail: string;
}

/** Read-only drift report; consumed by `check` and `sync`. */
export async function verify(
  root: string,
  options: VerifyOptions,
): Promise<ProjectionDrift[]> {
  return options.mode === "symlink"
    ? verifySymlinks(root)
    : verifyCopies(root, options.hashes);
}

async function projectSymlinks(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  const git = await detectGitSymlinks(root);
  if (git.isGitRepo && git.coreSymlinks === "false") {
    throw new CliError(
      "git config core.symlinks is false: git would index the links as regular files. Run `git config core.symlinks true` or switch modes with `agentsdir sync --mode copy`.",
      EXIT_CODES.driftOrInvariant,
    );
  }
  const pending = new Set(options.pendingRemovals ?? []);
  const changes: ProjectionChange[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const expected = relativeLinkTarget(spec);
    const absTarget = toAbsolute(root, spec.target);
    const state = (await willBeRemoved(root, spec.target, spec.kind, pending))
      ? "absent"
      : await classifyLinkTarget(absTarget, expected);
    if (state === "correct") {
      changes.push({ path: spec.target, action: "unchanged", existed: true });
      continue;
    }
    if (state === "foreign") {
      throw foreignTargetError(spec.target);
    }
    changes.push({
      path: spec.target,
      action: "link",
      existed: state !== "absent",
    });
    if (options.dryRun) {
      continue;
    }
    // same guard as projectCopies: `mkdir -p` walks through a linked parent,
    // and the `unlink` below would delete a link of the user's, outside the repo
    await ensureNoLinkedParent(root, spec.target);
    if (state === "other-link" || state === "materialized") {
      await unlink(absTarget);
    }
    await mkdir(dirname(absTarget), { recursive: true });
    await symlink(expected, absTarget, spec.kind === "dir" ? "dir" : "file");
    if (!(await lstat(absTarget)).isSymbolicLink()) {
      throw new CliError(
        `${spec.target} did not materialize as a real symlink. Switch modes with \`agentsdir sync --mode copy\`.`,
        EXIT_CODES.driftOrInvariant,
      );
    }
  }
  return { changes, hashes: {} };
}

async function projectCopies(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  const previousHashes = options.previousHashes ?? {};
  const pending = new Set(options.pendingRemovals ?? []);
  const changes: ProjectionChange[] = [];
  const hashes: Record<string, string> = {};
  for (const file of await expectedCopies(root, options.overlay ?? {})) {
    hashes[file.path] = sha256(file.content);
    const absTarget = toAbsolute(root, file.path);
    const state = (await willBeRemoved(root, file.path, "file", pending))
      ? "absent"
      : await classifyCopyTarget(absTarget, file, previousHashes);
    if (state === "unchanged") {
      changes.push({ path: file.path, action: "unchanged", existed: true });
      continue;
    }
    if (state === "foreign") {
      throw foreignTargetError(file.path);
    }
    changes.push({
      path: file.path,
      action: "write",
      existed: state !== "absent",
    });
    if (options.dryRun) {
      continue;
    }
    await ensureNoLinkedParent(root, file.path);
    await mkdir(dirname(absTarget), { recursive: true });
    await writeFileAtomic(absTarget, file.content);
  }
  return { changes, hashes };
}

/**
 * Refuses to project into a directory that is a symlink. `mkdir -p` walks
 * happily through one, so a repository shipping `.claude/rules` as a link to
 * somewhere else had its projections written outside the git root — and the
 * write itself looked perfectly ordinary in the report.
 */
export async function ensureNoLinkedParent(
  root: string,
  relPath: string,
): Promise<void> {
  const parts = relPath.split("/");
  for (let depth = 1; depth < parts.length; depth += 1) {
    const branch = parts.slice(0, depth).join("/");
    let stats;
    try {
      stats = await lstat(toAbsolute(root, branch));
    } catch {
      continue; // not created yet: mkdir will make a real directory
    }
    if (stats.isSymbolicLink()) {
      throw new CliError(
        `Refusing to write into ${branch}: it is a symlink, and projecting through it would write outside the repository. Replace it with a real directory, then run the command again.`,
        EXIT_CODES.driftOrInvariant,
      );
    }
  }
}

async function verifySymlinks(root: string): Promise<ProjectionDrift[]> {
  const drifts: ProjectionDrift[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const absTarget = toAbsolute(root, spec.target);
    let stats;
    try {
      stats = await lstat(absTarget);
    } catch {
      drifts.push({
        path: spec.target,
        kind: "missing",
        detail: "projection missing — run `agentsdir sync`.",
      });
      continue;
    }
    if (!stats.isSymbolicLink()) {
      const ours = await isMaterializedLink(
        absTarget,
        stats.isFile(),
        relativeLinkTarget(spec),
      );
      drifts.push({
        path: spec.target,
        kind: "replaced-by-copy",
        detail: ours
          ? "symlink materialized as a text file by a checkout without symlink support — run `agentsdir sync` to restore the link, or `agentsdir sync --mode copy` to switch this repo to copy mode."
          : "expected a symlink but found a regular file or directory that agentsdir did not generate — move its content into .agents/ and delete it, then run `agentsdir sync`.",
      });
      continue;
    }
    const current = normalizeLink(await readlink(absTarget));
    const expected = relativeLinkTarget(spec);
    if (current !== expected) {
      drifts.push({
        path: spec.target,
        kind: "modified",
        detail: `link points to ${current} instead of ${expected} — run \`agentsdir sync\`.`,
      });
    }
  }
  return drifts;
}

async function verifyCopies(
  root: string,
  hashes: Record<string, string>,
): Promise<ProjectionDrift[]> {
  const drifts: ProjectionDrift[] = [];
  // the source of truth is the reference, not the fingerprint of the last sync:
  // comparing to the recorded hash alone would call a copy correct while its
  // source has moved on — the most common drift of all (edit, forget to sync)
  const expected = new Map(
    (await expectedCopies(root, {})).map((file) => [file.path, file]),
  );
  for (const [path, file] of [...expected].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  )) {
    let current: Buffer;
    try {
      current = await readFile(toAbsolute(root, path));
    } catch (error) {
      // an unreadable projection is not a missing one, and `sync` will not
      // recreate it: say which of the two the user is looking at
      const code = (error as NodeJS.ErrnoException).code;
      drifts.push({
        path,
        kind: "missing",
        detail:
          code === "ENOENT"
            ? "projection missing — run `agentsdir sync`."
            : `projection cannot be read (${code ?? "unknown error"}) — fix its permissions or restore it; \`sync\` cannot repair what it cannot read.`,
      });
      continue;
    }
    if (current.equals(file.content)) {
      continue;
    }
    if (
      file.isMarkdown &&
      !current.toString("utf8").includes(GENERATED_HEADER)
    ) {
      drifts.push({
        path,
        kind: "header-removed",
        detail:
          "the generated header was removed — edit the source in .agents/ and run `agentsdir sync`.",
      });
      continue;
    }
    // matching the recorded fingerprint means the copy is intact but stale:
    // its source changed since the last sync
    drifts.push(
      hashes[path] === sha256(current)
        ? {
            path,
            kind: "stale",
            detail:
              "the source in .agents/ changed since the last sync — run `agentsdir sync`.",
          }
        : {
            path,
            kind: "modified",
            detail:
              "content differs from the source of truth — move your edits into .agents/ and run `agentsdir sync`.",
          },
    );
  }
  // recorded projections whose source is gone: sync removes them
  const reported = new Set<string>();
  for (const path of Object.keys(hashes).sort()) {
    if (expected.has(path) || !(await entryExists(toAbsolute(root, path)))) {
      continue;
    }
    reported.add(path);
    drifts.push({
      path,
      kind: "orphan",
      detail:
        "projection left behind by a deleted source — run `agentsdir sync` to remove it.",
    });
  }
  // and what the fingerprints never knew about. Scanning only the recorded
  // hashes left a whole class invisible: a folder dropped into .claude/skills/
  // that never had a source is read by neither pass — while the harness loads
  // it. Enumerating the projected directories is the only way to see it.
  for (const path of await projectedFiles(root)) {
    if (expected.has(path) || reported.has(path)) {
      continue;
    }
    drifts.push({
      path,
      kind: "orphan",
      detail:
        "no source in .agents/ produces this file, yet the harness loads it — move it into the source of truth, or run `agentsdir sync` to remove it.",
    });
  }
  return drifts;
}

/** Every file currently sitting under the projected directories. */
async function projectedFiles(root: string): Promise<string[]> {
  const paths: string[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    for (const file of await walkFiles(
      toAbsolute(root, spec.target),
      spec.target,
    )) {
      paths.push(file.rel);
    }
  }
  return paths.sort();
}

interface ExpectedCopy {
  path: string;
  content: Buffer;
  isMarkdown: boolean;
}

async function expectedCopies(
  root: string,
  overlay: Record<string, Buffer>,
): Promise<ExpectedCopy[]> {
  const files: ExpectedCopy[] = [
    {
      path: "CLAUDE.md",
      content: Buffer.from(CLAUDE_MD_COPY, "utf8"),
      isMarkdown: true,
    },
  ];
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    // the source directory itself may be a link: readdir walks through it and
    // every entry then lstats as a real file, so outside content would be
    // copied into versioned projections
    await ensureNoLinkedParent(root, `${spec.source}/.`);
    const seenSources = new Set<string>();
    for (const source of await walkFiles(
      toAbsolute(root, spec.source),
      spec.target,
    )) {
      const sourceRel = spec.source + source.rel.slice(spec.target.length);
      seenSources.add(sourceRel);
      const raw = overlay[sourceRel] ?? (await readFile(source.abs));
      files.push(toExpectedCopy(source.rel, raw));
    }
    // overlay entries for source files absent from disk (e.g. a regenerated
    // artifact planned but not written yet), appended in sorted order
    const extras = Object.keys(overlay)
      .filter(
        (key) => key.startsWith(`${spec.source}/`) && !seenSources.has(key),
      )
      .sort();
    for (const key of extras) {
      const rel = spec.target + key.slice(spec.source.length);
      files.push(toExpectedCopy(rel, overlay[key] ?? Buffer.alloc(0)));
    }
  }
  return files;
}

function toExpectedCopy(rel: string, raw: Buffer): ExpectedCopy {
  if (rel.endsWith(".md")) {
    return {
      path: rel,
      content: Buffer.from(decorateMarkdown(raw.toString("utf8")), "utf8"),
      isMarkdown: true,
    };
  }
  return { path: rel, content: raw, isMarkdown: false };
}

/**
 * The generated header, placed where it cannot hide a frontmatter block.
 *
 * Claude Code only reads frontmatter that opens the file: prefixing the header
 * to a SKILL.md or a sub-agent left the projection byte-correct and
 * functionally dead — `check` was green while the sub-agent never reached the
 * delegation list and the skill was announced by the comment instead of its
 * description. A source that opens with a frontmatter block therefore keeps it
 * first and takes the header right after; everything else is prefixed as
 * before. Unparseable frontmatter is not ours to repair: it falls back to the
 * prefix.
 */
function decorateMarkdown(source: string): string {
  const blockLength = frontmatterBlockLength(source);
  if (blockLength === 0) {
    return `${MD_HEADER_LINE}\n\n${source}`;
  }
  const block = source.slice(0, blockLength);
  const rest = source.slice(blockLength);
  // a closing `---` at end of file matches without its newline
  const separator = block.endsWith("\n") ? "" : "\n";
  return `${block}${separator}\n${MD_HEADER_LINE}\n${rest === "" ? "" : `\n${rest}`}`;
}

/** Recursive, sorted by name (code units) so every output is deterministic. */
async function walkFiles(
  absDir: string,
  relPrefix: string,
): Promise<{ rel: string; abs: string }[]> {
  // an absent mirror is normal (nothing projected yet); an unreadable one is a
  // fault, and must never read as "empty" — that would delete live projections
  let entries;
  try {
    entries = await readdir(absDir, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return [];
    }
    throw new CliError(
      `Cannot read ${absDir} (${(error as NodeJS.ErrnoException).code ?? "unknown error"}). Fix its permissions or restore it — refusing to treat an unreadable directory as an empty one.`,
      EXIT_CODES.environmentOrUsage,
    );
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const files: { rel: string; abs: string }[] = [];
  for (const entry of entries) {
    const rel = `${relPrefix}/${entry.name}`;
    const abs = join(absDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkFiles(abs, rel)));
    } else if (entry.isFile()) {
      files.push({ rel, abs });
    }
  }
  return files;
}

async function classifyLinkTarget(
  absTarget: string,
  expected: string,
): Promise<"correct" | "other-link" | "absent" | "foreign" | "materialized"> {
  let stats;
  try {
    stats = await lstat(absTarget);
  } catch {
    return "absent";
  }
  if (!stats.isSymbolicLink()) {
    return (await isMaterializedLink(absTarget, stats.isFile(), expected))
      ? "materialized"
      : "foreign";
  }
  return normalizeLink(await readlink(absTarget)) === expected
    ? "correct"
    : "other-link";
}

/**
 * A checkout without symlink support writes the link target as the file
 * content — the very case this product exists to cover. Such a file is ours,
 * not a stranger: treating it as foreign left  telling the user to run
 * , and  refusing, with no way out but a manual delete that no
 * message mentioned.
 */
async function isMaterializedLink(
  absTarget: string,
  isFile: boolean,
  expected: string,
): Promise<boolean> {
  if (!isFile) {
    return false;
  }
  try {
    const content = await readFile(absTarget, "utf8");
    // git writes the target verbatim, without a trailing newline; be lenient
    return normalizeLink(content.trim()) === expected;
  } catch {
    return false;
  }
}

async function classifyCopyTarget(
  absTarget: string,
  file: ExpectedCopy,
  previousHashes: Record<string, string>,
): Promise<"absent" | "unchanged" | "stale-ours" | "foreign"> {
  let current: Buffer;
  try {
    current = await readFile(absTarget);
  } catch {
    return "absent";
  }
  if (current.equals(file.content)) {
    return "unchanged";
  }
  if (file.isMarkdown && current.toString("utf8").includes(GENERATED_HEADER)) {
    return "stale-ours";
  }
  if (previousHashes[file.path] === sha256(current)) {
    return "stale-ours";
  }
  // a strict prefix of what we would write is a write killed mid-file, not a
  // file someone edited: editing adds or changes bytes, it does not truncate to
  // an exact prefix. Repairing it keeps `check` and `sync` from deadlocking,
  // while an actual hand edit still lands on "foreign" and is refused
  if (
    previousHashes[file.path] !== undefined &&
    current.length < file.content.length &&
    file.content.subarray(0, current.length).equals(current)
  ) {
    return "stale-ours";
  }
  return "foreign";
}

function relativeLinkTarget(spec: ProjectionSpec): string {
  const depth = spec.target.split("/").length - 1;
  return `${"../".repeat(depth)}${spec.source}`;
}

function foreignTargetError(path: string): CliError {
  return new CliError(
    `${path} already exists and was not generated by agentsdir. Move its content into .agents/ (rules, skills) or into AGENTS.md, delete ${path}, then run the command again. Importing an existing configuration in one step is what \`agentsdir migrate\` will do, once it exists.`,
    EXIT_CODES.driftOrInvariant,
  );
}

function normalizeLink(target: string): string {
  return target.replaceAll("\\", "/");
}

function toAbsolute(root: string, posixPath: string): string {
  // paths here can come from the manifest of a cloned repository: confine them
  return resolveInsideRepo(root, posixPath);
}

function sha256(content: Buffer): string {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}
