import { entryExists, resolveInsideRepo, writeFileAtomic } from "./fs-utils.js";
import { createHash } from "node:crypto";
import {
  lstat,
  mkdir,
  readdir,
  readFile,
  readlink,
  rm,
  symlink,
  unlink,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { EXIT_CODES } from "../exit-codes.js";
import { detectGitSymlinks } from "./detect.js";
import { CliError } from "./errors.js";
import type { ProjectionMode } from "./manifest.js";

export const GENERATED_HEADER =
  "GENERATED by agentsdir — edit the source in .agents/ and run `agentsdir sync`.";

const MD_HEADER_LINE = `<!-- ${GENERATED_HEADER} -->`;

/**
 * Copy-mode CLAUDE.md is a bridge, not a copy: Claude Code reads AGENTS.md
 * through the `@AGENTS.md` import, so there is a single source either way.
 */
export const CLAUDE_MD_COPY = `@AGENTS.md\n\n${MD_HEADER_LINE}\n`;

export interface ProjectionSpec {
  /** Repo-relative target, POSIX. */
  target: string;
  /** Repo-relative source, POSIX. */
  source: string;
  kind: "file" | "dir";
}

/** Claude Code projections: the CLAUDE.md bridge and three directory mirrors. */
export const CLAUDE_PROJECTIONS: readonly ProjectionSpec[] = [
  { target: "CLAUDE.md", source: "AGENTS.md", kind: "file" },
  { target: ".claude/rules", source: ".agents/rules", kind: "dir" },
  { target: ".claude/skills", source: ".agents/skills", kind: "dir" },
  { target: ".claude/agents", source: ".agents/agents", kind: "dir" },
];

export interface ProjectOptions {
  /** Comes from the manifest — never recomputed silently. */
  mode: ProjectionMode;
  dryRun?: boolean;
  /** Copy mode: fingerprints recorded by the previous run, to recognize our stale copies. */
  previousHashes?: Record<string, string>;
  /**
   * Copy mode: would-be content of source files (repo-relative POSIX paths),
   * so a dry run computes the same plan as a run that writes those sources
   * first (`sync` regenerates Codex artifacts before projecting them).
   */
  overlay?: Record<string, Buffer>;
  /**
   * Plans against a clean slate instead of the current disk: what a mode
   * switch will find once `unproject` has removed the previous mode's
   * projections. Dry run only — a writing run must classify the real disk.
   */
  assumeAbsent?: boolean;
}

export interface ProjectionChange {
  path: string;
  action: "link" | "write" | "unchanged";
  /** False when the target did not exist before this run (created vs updated). */
  existed: boolean;
}

export interface ProjectionResult {
  changes: ProjectionChange[];
  /** Copy mode: sha256 fingerprint of every generated file, for [projections.hashes]. */
  hashes: Record<string, string>;
}

/** Materializes the projections. Never overwrites a file it does not own (exit 1). */
export async function project(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  return options.mode === "symlink"
    ? projectSymlinks(root, options)
    : projectCopies(root, options);
}

export interface RefreshOptions {
  /** Mode to project into — the one the manifest will record. */
  mode: ProjectionMode;
  /** Mode currently recorded; when it differs from `mode`, this is a switch. */
  previousMode: ProjectionMode;
  /** Fingerprints recorded by the previous run. */
  previousHashes: Record<string, string>;
  /** Would-be content of source files about to be written (repo-relative POSIX). */
  overlay?: Record<string, Buffer>;
  dryRun?: boolean;
}

export interface RefreshResult extends ProjectionResult {
  /** Projections removed before this run projected: stale mode, or orphans. */
  removed: string[];
}

/**
 * Brings the projections back in line with the source of truth: first removes
 * what must not survive — the previous mode's projections on a switch, the
 * copies whose source is gone otherwise — then projects. `sync` and the
 * generators share this single orchestration; the caller stays responsible for
 * recording the returned fingerprints in the manifest.
 */
export async function refreshProjections(
  root: string,
  options: RefreshOptions,
): Promise<RefreshResult> {
  const switching = options.mode !== options.previousMode;
  const { removed } = switching
    ? await unproject(root, {
        mode: options.previousMode,
        dryRun: options.dryRun,
        previousHashes: options.previousHashes,
      })
    : await removeOrphanProjections(root, {
        mode: options.mode,
        hashes: options.previousHashes,
        dryRun: options.dryRun,
      });
  const projection = await project(root, {
    mode: options.mode,
    dryRun: options.dryRun,
    // on a switch the recorded fingerprints describe the mode being left
    previousHashes: switching ? {} : options.previousHashes,
    ...(options.overlay === undefined ? {} : { overlay: options.overlay }),
    // a dry run plans against the clean slate the removal above would leave
    ...(switching && options.dryRun === true ? { assumeAbsent: true } : {}),
  });
  return { ...projection, removed };
}

export interface UnprojectOptions {
  /** Mode whose projections are being removed — the one leaving the manifest. */
  mode: ProjectionMode;
  dryRun?: boolean;
  /** Copy mode: fingerprints recorded by the previous run, to recognize our copies. */
  previousHashes?: Record<string, string>;
}

/**
 * Removes the projections of `mode` before the other mode is materialized.
 * Only what agentsdir owns is deleted — a correct link, or a copy matching its
 * recorded fingerprint or carrying the generated header. Anything else is left
 * on disk, where projecting the new mode reports it as a foreign target.
 */
export async function unproject(
  root: string,
  options: UnprojectOptions,
): Promise<{ removed: string[] }> {
  const removed =
    options.mode === "symlink"
      ? await ownedSymlinks(root)
      : await ownedCopies(root, options.previousHashes ?? {});
  if (!options.dryRun) {
    for (const path of removed) {
      await rm(toAbsolute(root, path), { force: true });
    }
    // the mirrors are ours; leftover entries keep the directory
    for (const spec of CLAUDE_PROJECTIONS) {
      if (spec.kind === "dir") {
        await rmdirIfEmpty(root, spec.target);
      }
    }
  }
  return { removed };
}

async function ownedSymlinks(root: string): Promise<string[]> {
  const owned: string[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const state = await classifyLinkTarget(
      toAbsolute(root, spec.target),
      relativeLinkTarget(spec),
    );
    if (state === "correct") {
      owned.push(spec.target);
    }
  }
  return owned;
}

async function ownedCopies(
  root: string,
  previousHashes: Record<string, string>,
): Promise<string[]> {
  const candidates = new Set<string>(Object.keys(previousHashes));
  candidates.add("CLAUDE.md");
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    for (const file of await walkFiles(
      toAbsolute(root, spec.target),
      spec.target,
    )) {
      candidates.add(file.rel);
    }
  }
  const owned: string[] = [];
  for (const path of [...candidates].sort()) {
    let current: Buffer;
    try {
      current = await readFile(toAbsolute(root, path));
    } catch {
      continue;
    }
    const ours =
      previousHashes[path] === sha256(current) ||
      (path.endsWith(".md") &&
        current.toString("utf8").includes(GENERATED_HEADER));
    if (ours) {
      owned.push(path);
    }
  }
  return owned;
}

/**
 * Copies left behind by a deleted source (a rule removed from `.agents/rules/`
 * keeps its `.claude/rules/` mirror otherwise). Symlink mode has none: its four
 * targets are fixed and always point at a live source.
 */
export async function removeOrphanProjections(
  root: string,
  options: {
    mode: ProjectionMode;
    hashes: Record<string, string>;
    dryRun?: boolean;
  },
): Promise<{ removed: string[] }> {
  if (options.mode === "symlink") {
    return { removed: [] };
  }
  const expected = new Set(
    (await expectedCopies(root, {})).map((file) => file.path),
  );
  const removed: string[] = [];
  for (const path of Object.keys(options.hashes).sort()) {
    if (expected.has(path) || !(await entryExists(toAbsolute(root, path)))) {
      continue;
    }
    removed.push(path);
  }
  if (!options.dryRun) {
    for (const path of removed) {
      await rm(toAbsolute(root, path), { force: true });
    }
    for (const spec of CLAUDE_PROJECTIONS) {
      if (spec.kind === "dir") {
        await rmdirIfEmpty(root, spec.target);
      }
    }
  }
  return { removed };
}

async function rmdirIfEmpty(root: string, path: string): Promise<void> {
  const abs = toAbsolute(root, path);
  try {
    if ((await readdir(abs)).length === 0) {
      await rm(abs, { recursive: true, force: true });
    }
  } catch {
    // absent or not a directory: nothing to clean up
  }
}

export interface VerifyOptions {
  mode: ProjectionMode;
  /** Copy mode: fingerprints recorded in the manifest. */
  hashes: Record<string, string>;
}

export type DriftKind =
  | "missing"
  | "modified"
  | "replaced-by-copy"
  | "header-removed"
  | "stale"
  | "orphan";

export interface ProjectionDrift {
  path: string;
  kind: DriftKind;
  detail: string;
}

/** Read-only drift report; consumed by `check` and `sync`. */
export async function verify(
  root: string,
  options: VerifyOptions,
): Promise<ProjectionDrift[]> {
  return options.mode === "symlink"
    ? verifySymlinks(root)
    : verifyCopies(root, options.hashes);
}

async function projectSymlinks(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  const git = await detectGitSymlinks(root);
  if (git.isGitRepo && git.coreSymlinks === "false") {
    throw new CliError(
      "git config core.symlinks is false: git would index the links as regular files. Run `git config core.symlinks true` or switch modes with `agentsdir sync --mode copy`.",
      EXIT_CODES.driftOrInvariant,
    );
  }
  const changes: ProjectionChange[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const expected = relativeLinkTarget(spec);
    const absTarget = toAbsolute(root, spec.target);
    const state =
      options.assumeAbsent === true
        ? "absent"
        : await classifyLinkTarget(absTarget, expected);
    if (state === "correct") {
      changes.push({ path: spec.target, action: "unchanged", existed: true });
      continue;
    }
    if (state === "foreign") {
      throw foreignTargetError(spec.target);
    }
    changes.push({
      path: spec.target,
      action: "link",
      existed: state !== "absent",
    });
    if (options.dryRun) {
      continue;
    }
    // same guard as projectCopies: `mkdir -p` walks through a linked parent,
    // and the `unlink` below would delete a link of the user's, outside the repo
    await ensureNoLinkedParent(root, spec.target);
    if (state === "other-link") {
      await unlink(absTarget);
    }
    await mkdir(dirname(absTarget), { recursive: true });
    await symlink(expected, absTarget, spec.kind === "dir" ? "dir" : "file");
    if (!(await lstat(absTarget)).isSymbolicLink()) {
      throw new CliError(
        `${spec.target} did not materialize as a real symlink. Switch modes with \`agentsdir sync --mode copy\`.`,
        EXIT_CODES.driftOrInvariant,
      );
    }
  }
  return { changes, hashes: {} };
}

async function projectCopies(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  const previousHashes = options.previousHashes ?? {};
  const changes: ProjectionChange[] = [];
  const hashes: Record<string, string> = {};
  for (const file of await expectedCopies(root, options.overlay ?? {})) {
    hashes[file.path] = sha256(file.content);
    const absTarget = toAbsolute(root, file.path);
    const state =
      options.assumeAbsent === true
        ? "absent"
        : await classifyCopyTarget(absTarget, file, previousHashes);
    if (state === "unchanged") {
      changes.push({ path: file.path, action: "unchanged", existed: true });
      continue;
    }
    if (state === "foreign") {
      throw foreignTargetError(file.path);
    }
    changes.push({
      path: file.path,
      action: "write",
      existed: state !== "absent",
    });
    if (options.dryRun) {
      continue;
    }
    await ensureNoLinkedParent(root, file.path);
    await mkdir(dirname(absTarget), { recursive: true });
    await writeFileAtomic(absTarget, file.content);
  }
  return { changes, hashes };
}

/**
 * Refuses to project into a directory that is a symlink. `mkdir -p` walks
 * happily through one, so a repository shipping `.claude/rules` as a link to
 * somewhere else had its projections written outside the git root — and the
 * write itself looked perfectly ordinary in the report.
 */
export async function ensureNoLinkedParent(
  root: string,
  relPath: string,
): Promise<void> {
  const parts = relPath.split("/");
  for (let depth = 1; depth < parts.length; depth += 1) {
    const branch = parts.slice(0, depth).join("/");
    let stats;
    try {
      stats = await lstat(toAbsolute(root, branch));
    } catch {
      continue; // not created yet: mkdir will make a real directory
    }
    if (stats.isSymbolicLink()) {
      throw new CliError(
        `Refusing to write into ${branch}: it is a symlink, and projecting through it would write outside the repository. Replace it with a real directory, then run the command again.`,
        EXIT_CODES.driftOrInvariant,
      );
    }
  }
}

async function verifySymlinks(root: string): Promise<ProjectionDrift[]> {
  const drifts: ProjectionDrift[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const absTarget = toAbsolute(root, spec.target);
    let stats;
    try {
      stats = await lstat(absTarget);
    } catch {
      drifts.push({
        path: spec.target,
        kind: "missing",
        detail: "projection missing — run `agentsdir sync`.",
      });
      continue;
    }
    if (!stats.isSymbolicLink()) {
      drifts.push({
        path: spec.target,
        kind: "replaced-by-copy",
        detail:
          "expected a symlink but found a regular file or directory — run `agentsdir sync`.",
      });
      continue;
    }
    const current = normalizeLink(await readlink(absTarget));
    const expected = relativeLinkTarget(spec);
    if (current !== expected) {
      drifts.push({
        path: spec.target,
        kind: "modified",
        detail: `link points to ${current} instead of ${expected} — run \`agentsdir sync\`.`,
      });
    }
  }
  return drifts;
}

async function verifyCopies(
  root: string,
  hashes: Record<string, string>,
): Promise<ProjectionDrift[]> {
  const drifts: ProjectionDrift[] = [];
  // the source of truth is the reference, not the fingerprint of the last sync:
  // comparing to the recorded hash alone would call a copy correct while its
  // source has moved on — the most common drift of all (edit, forget to sync)
  const expected = new Map(
    (await expectedCopies(root, {})).map((file) => [file.path, file]),
  );
  for (const [path, file] of [...expected].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  )) {
    let current: Buffer;
    try {
      current = await readFile(toAbsolute(root, path));
    } catch (error) {
      // an unreadable projection is not a missing one, and `sync` will not
      // recreate it: say which of the two the user is looking at
      const code = (error as NodeJS.ErrnoException).code;
      drifts.push({
        path,
        kind: "missing",
        detail:
          code === "ENOENT"
            ? "projection missing — run `agentsdir sync`."
            : `projection cannot be read (${code ?? "unknown error"}) — fix its permissions or restore it; \`sync\` cannot repair what it cannot read.`,
      });
      continue;
    }
    if (current.equals(file.content)) {
      continue;
    }
    if (
      file.isMarkdown &&
      !current.toString("utf8").includes(GENERATED_HEADER)
    ) {
      drifts.push({
        path,
        kind: "header-removed",
        detail:
          "the generated header was removed — edit the source in .agents/ and run `agentsdir sync`.",
      });
      continue;
    }
    // matching the recorded fingerprint means the copy is intact but stale:
    // its source changed since the last sync
    drifts.push(
      hashes[path] === sha256(current)
        ? {
            path,
            kind: "stale",
            detail:
              "the source in .agents/ changed since the last sync — run `agentsdir sync`.",
          }
        : {
            path,
            kind: "modified",
            detail:
              "content differs from the source of truth — move your edits into .agents/ and run `agentsdir sync`.",
          },
    );
  }
  // recorded projections whose source is gone: sync removes them
  for (const path of Object.keys(hashes).sort()) {
    if (expected.has(path) || !(await entryExists(toAbsolute(root, path)))) {
      continue;
    }
    drifts.push({
      path,
      kind: "orphan",
      detail:
        "projection left behind by a deleted source — run `agentsdir sync` to remove it.",
    });
  }
  return drifts;
}

interface ExpectedCopy {
  path: string;
  content: Buffer;
  isMarkdown: boolean;
}

async function expectedCopies(
  root: string,
  overlay: Record<string, Buffer>,
): Promise<ExpectedCopy[]> {
  const files: ExpectedCopy[] = [
    {
      path: "CLAUDE.md",
      content: Buffer.from(CLAUDE_MD_COPY, "utf8"),
      isMarkdown: true,
    },
  ];
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    // the source directory itself may be a link: readdir walks through it and
    // every entry then lstats as a real file, so outside content would be
    // copied into versioned projections
    await ensureNoLinkedParent(root, `${spec.source}/.`);
    const seenSources = new Set<string>();
    for (const source of await walkFiles(
      toAbsolute(root, spec.source),
      spec.target,
    )) {
      const sourceRel = spec.source + source.rel.slice(spec.target.length);
      seenSources.add(sourceRel);
      const raw = overlay[sourceRel] ?? (await readFile(source.abs));
      files.push(toExpectedCopy(source.rel, raw));
    }
    // overlay entries for source files absent from disk (e.g. a regenerated
    // artifact planned but not written yet), appended in sorted order
    const extras = Object.keys(overlay)
      .filter(
        (key) => key.startsWith(`${spec.source}/`) && !seenSources.has(key),
      )
      .sort();
    for (const key of extras) {
      const rel = spec.target + key.slice(spec.source.length);
      files.push(toExpectedCopy(rel, overlay[key] ?? Buffer.alloc(0)));
    }
  }
  return files;
}

function toExpectedCopy(rel: string, raw: Buffer): ExpectedCopy {
  if (rel.endsWith(".md")) {
    const decorated = `${MD_HEADER_LINE}\n\n${raw.toString("utf8")}`;
    return {
      path: rel,
      content: Buffer.from(decorated, "utf8"),
      isMarkdown: true,
    };
  }
  return { path: rel, content: raw, isMarkdown: false };
}

/** Recursive, sorted by name (code units) so every output is deterministic. */
async function walkFiles(
  absDir: string,
  relPrefix: string,
): Promise<{ rel: string; abs: string }[]> {
  // an absent mirror is normal (nothing projected yet); an unreadable one is a
  // fault, and must never read as "empty" — that would delete live projections
  let entries;
  try {
    entries = await readdir(absDir, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return [];
    }
    throw new CliError(
      `Cannot read ${absDir} (${(error as NodeJS.ErrnoException).code ?? "unknown error"}). Fix its permissions or restore it — refusing to treat an unreadable directory as an empty one.`,
      EXIT_CODES.environmentOrUsage,
    );
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const files: { rel: string; abs: string }[] = [];
  for (const entry of entries) {
    const rel = `${relPrefix}/${entry.name}`;
    const abs = join(absDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkFiles(abs, rel)));
    } else if (entry.isFile()) {
      files.push({ rel, abs });
    }
  }
  return files;
}

async function classifyLinkTarget(
  absTarget: string,
  expected: string,
): Promise<"correct" | "other-link" | "absent" | "foreign"> {
  let stats;
  try {
    stats = await lstat(absTarget);
  } catch {
    return "absent";
  }
  if (!stats.isSymbolicLink()) {
    return "foreign";
  }
  return normalizeLink(await readlink(absTarget)) === expected
    ? "correct"
    : "other-link";
}

async function classifyCopyTarget(
  absTarget: string,
  file: ExpectedCopy,
  previousHashes: Record<string, string>,
): Promise<"absent" | "unchanged" | "stale-ours" | "foreign"> {
  let current: Buffer;
  try {
    current = await readFile(absTarget);
  } catch {
    return "absent";
  }
  if (current.equals(file.content)) {
    return "unchanged";
  }
  if (file.isMarkdown && current.toString("utf8").includes(GENERATED_HEADER)) {
    return "stale-ours";
  }
  if (previousHashes[file.path] === sha256(current)) {
    return "stale-ours";
  }
  // a strict prefix of what we would write is a write killed mid-file, not a
  // file someone edited: editing adds or changes bytes, it does not truncate to
  // an exact prefix. Repairing it keeps `check` and `sync` from deadlocking,
  // while an actual hand edit still lands on "foreign" and is refused
  if (
    previousHashes[file.path] !== undefined &&
    current.length < file.content.length &&
    file.content.subarray(0, current.length).equals(current)
  ) {
    return "stale-ours";
  }
  return "foreign";
}

function relativeLinkTarget(spec: ProjectionSpec): string {
  const depth = spec.target.split("/").length - 1;
  return `${"../".repeat(depth)}${spec.source}`;
}

function foreignTargetError(path: string): CliError {
  return new CliError(
    `${path} already exists and was not generated by agentsdir. Move its content into the source of truth (.agents/ or AGENTS.md) and delete the file, then rerun — or wait for \`agentsdir migrate\`.`,
    EXIT_CODES.driftOrInvariant,
  );
}

function normalizeLink(target: string): string {
  return target.replaceAll("\\", "/");
}

function toAbsolute(root: string, posixPath: string): string {
  // paths here can come from the manifest of a cloned repository: confine them
  return resolveInsideRepo(root, posixPath);
}

function sha256(content: Buffer): string {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}
