import { createHash } from "node:crypto";
import {
  lstat,
  mkdir,
  readdir,
  readFile,
  readlink,
  rm,
  symlink,
  unlink,
  writeFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { EXIT_CODES } from "../exit-codes.js";
import { detectGitSymlinks } from "./detect.js";
import { CliError } from "./errors.js";
import type { ProjectionMode } from "./manifest.js";

export const GENERATED_HEADER =
  "GENERATED by agentsdir — edit the source in .agents/ and run `agentsdir sync`.";

const MD_HEADER_LINE = `<!-- ${GENERATED_HEADER} -->`;

/**
 * Copy-mode CLAUDE.md is a bridge, not a copy: Claude Code reads AGENTS.md
 * through the `@AGENTS.md` import, so there is a single source either way.
 */
export const CLAUDE_MD_COPY = `@AGENTS.md\n\n${MD_HEADER_LINE}\n`;

export interface ProjectionSpec {
  /** Repo-relative target, POSIX. */
  target: string;
  /** Repo-relative source, POSIX. */
  source: string;
  kind: "file" | "dir";
}

/** Claude Code projections: the CLAUDE.md bridge and three directory mirrors. */
export const CLAUDE_PROJECTIONS: readonly ProjectionSpec[] = [
  { target: "CLAUDE.md", source: "AGENTS.md", kind: "file" },
  { target: ".claude/rules", source: ".agents/rules", kind: "dir" },
  { target: ".claude/skills", source: ".agents/skills", kind: "dir" },
  { target: ".claude/agents", source: ".agents/agents", kind: "dir" },
];

export interface ProjectOptions {
  /** Comes from the manifest — never recomputed silently. */
  mode: ProjectionMode;
  dryRun?: boolean;
  /** Copy mode: fingerprints recorded by the previous run, to recognize our stale copies. */
  previousHashes?: Record<string, string>;
  /**
   * Copy mode: would-be content of source files (repo-relative POSIX paths),
   * so a dry run computes the same plan as a run that writes those sources
   * first (`sync` regenerates Codex artifacts before projecting them).
   */
  overlay?: Record<string, Buffer>;
  /**
   * Plans against a clean slate instead of the current disk: what a mode
   * switch will find once `unproject` has removed the previous mode's
   * projections. Dry run only — a writing run must classify the real disk.
   */
  assumeAbsent?: boolean;
}

export interface ProjectionChange {
  path: string;
  action: "link" | "write" | "unchanged";
  /** False when the target did not exist before this run (created vs updated). */
  existed: boolean;
}

export interface ProjectionResult {
  changes: ProjectionChange[];
  /** Copy mode: sha256 fingerprint of every generated file, for [projections.hashes]. */
  hashes: Record<string, string>;
}

/** Materializes the projections. Never overwrites a file it does not own (exit 1). */
export async function project(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  return options.mode === "symlink"
    ? projectSymlinks(root, options)
    : projectCopies(root, options);
}

export interface UnprojectOptions {
  /** Mode whose projections are being removed — the one leaving the manifest. */
  mode: ProjectionMode;
  dryRun?: boolean;
  /** Copy mode: fingerprints recorded by the previous run, to recognize our copies. */
  previousHashes?: Record<string, string>;
}

/**
 * Removes the projections of `mode` before the other mode is materialized.
 * Only what agentsdir owns is deleted — a correct link, or a copy matching its
 * recorded fingerprint or carrying the generated header. Anything else is left
 * on disk, where projecting the new mode reports it as a foreign target.
 */
export async function unproject(
  root: string,
  options: UnprojectOptions,
): Promise<{ removed: string[] }> {
  const removed =
    options.mode === "symlink"
      ? await ownedSymlinks(root)
      : await ownedCopies(root, options.previousHashes ?? {});
  if (!options.dryRun) {
    for (const path of removed) {
      await rm(toAbsolute(root, path), { force: true });
    }
    // the mirrors are ours; leftover entries keep the directory
    for (const spec of CLAUDE_PROJECTIONS) {
      if (spec.kind === "dir") {
        await rmdirIfEmpty(root, spec.target);
      }
    }
  }
  return { removed };
}

async function ownedSymlinks(root: string): Promise<string[]> {
  const owned: string[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const state = await classifyLinkTarget(
      toAbsolute(root, spec.target),
      relativeLinkTarget(spec),
    );
    if (state === "correct") {
      owned.push(spec.target);
    }
  }
  return owned;
}

async function ownedCopies(
  root: string,
  previousHashes: Record<string, string>,
): Promise<string[]> {
  const candidates = new Set<string>(Object.keys(previousHashes));
  candidates.add("CLAUDE.md");
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    for (const file of await walkFiles(
      toAbsolute(root, spec.target),
      spec.target,
    )) {
      candidates.add(file.rel);
    }
  }
  const owned: string[] = [];
  for (const path of [...candidates].sort()) {
    let current: Buffer;
    try {
      current = await readFile(toAbsolute(root, path));
    } catch {
      continue;
    }
    const ours =
      previousHashes[path] === sha256(current) ||
      (path.endsWith(".md") &&
        current.toString("utf8").includes(GENERATED_HEADER));
    if (ours) {
      owned.push(path);
    }
  }
  return owned;
}

async function rmdirIfEmpty(root: string, path: string): Promise<void> {
  const abs = toAbsolute(root, path);
  try {
    if ((await readdir(abs)).length === 0) {
      await rm(abs, { recursive: true, force: true });
    }
  } catch {
    // absent or not a directory: nothing to clean up
  }
}

export interface VerifyOptions {
  mode: ProjectionMode;
  /** Copy mode: fingerprints recorded in the manifest. */
  hashes: Record<string, string>;
}

export type DriftKind =
  "missing" | "modified" | "replaced-by-copy" | "header-removed";

export interface ProjectionDrift {
  path: string;
  kind: DriftKind;
  detail: string;
}

/** Read-only drift report; consumed by `check` and `sync`. */
export async function verify(
  root: string,
  options: VerifyOptions,
): Promise<ProjectionDrift[]> {
  return options.mode === "symlink"
    ? verifySymlinks(root)
    : verifyCopies(root, options.hashes);
}

async function projectSymlinks(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  const git = await detectGitSymlinks(root);
  if (git.isGitRepo && git.coreSymlinks === "false") {
    throw new CliError(
      "git config core.symlinks is false: git would index the links as regular files. Run `git config core.symlinks true` or switch modes with `agentsdir sync --mode copy`.",
      EXIT_CODES.driftOrInvariant,
    );
  }
  const changes: ProjectionChange[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const expected = relativeLinkTarget(spec);
    const absTarget = toAbsolute(root, spec.target);
    const state =
      options.assumeAbsent === true
        ? "absent"
        : await classifyLinkTarget(absTarget, expected);
    if (state === "correct") {
      changes.push({ path: spec.target, action: "unchanged", existed: true });
      continue;
    }
    if (state === "foreign") {
      throw foreignTargetError(spec.target);
    }
    changes.push({
      path: spec.target,
      action: "link",
      existed: state !== "absent",
    });
    if (options.dryRun) {
      continue;
    }
    if (state === "other-link") {
      await unlink(absTarget);
    }
    await mkdir(dirname(absTarget), { recursive: true });
    await symlink(expected, absTarget, spec.kind === "dir" ? "dir" : "file");
    if (!(await lstat(absTarget)).isSymbolicLink()) {
      throw new CliError(
        `${spec.target} did not materialize as a real symlink. Switch modes with \`agentsdir sync --mode copy\`.`,
        EXIT_CODES.driftOrInvariant,
      );
    }
  }
  return { changes, hashes: {} };
}

async function projectCopies(
  root: string,
  options: ProjectOptions,
): Promise<ProjectionResult> {
  const previousHashes = options.previousHashes ?? {};
  const changes: ProjectionChange[] = [];
  const hashes: Record<string, string> = {};
  for (const file of await expectedCopies(root, options.overlay ?? {})) {
    hashes[file.path] = sha256(file.content);
    const absTarget = toAbsolute(root, file.path);
    const state =
      options.assumeAbsent === true
        ? "absent"
        : await classifyCopyTarget(absTarget, file, previousHashes);
    if (state === "unchanged") {
      changes.push({ path: file.path, action: "unchanged", existed: true });
      continue;
    }
    if (state === "foreign") {
      throw foreignTargetError(file.path);
    }
    changes.push({
      path: file.path,
      action: "write",
      existed: state !== "absent",
    });
    if (options.dryRun) {
      continue;
    }
    await mkdir(dirname(absTarget), { recursive: true });
    await writeFile(absTarget, file.content);
  }
  return { changes, hashes };
}

async function verifySymlinks(root: string): Promise<ProjectionDrift[]> {
  const drifts: ProjectionDrift[] = [];
  for (const spec of CLAUDE_PROJECTIONS) {
    const absTarget = toAbsolute(root, spec.target);
    let stats;
    try {
      stats = await lstat(absTarget);
    } catch {
      drifts.push({
        path: spec.target,
        kind: "missing",
        detail: "projection missing — run `agentsdir sync`.",
      });
      continue;
    }
    if (!stats.isSymbolicLink()) {
      drifts.push({
        path: spec.target,
        kind: "replaced-by-copy",
        detail:
          "expected a symlink but found a regular file or directory — run `agentsdir sync`.",
      });
      continue;
    }
    const current = normalizeLink(await readlink(absTarget));
    const expected = relativeLinkTarget(spec);
    if (current !== expected) {
      drifts.push({
        path: spec.target,
        kind: "modified",
        detail: `link points to ${current} instead of ${expected} — run \`agentsdir sync\`.`,
      });
    }
  }
  return drifts;
}

async function verifyCopies(
  root: string,
  hashes: Record<string, string>,
): Promise<ProjectionDrift[]> {
  const drifts: ProjectionDrift[] = [];
  const entries = Object.entries(hashes).sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  );
  for (const [path, recorded] of entries) {
    let current: Buffer;
    try {
      current = await readFile(toAbsolute(root, path));
    } catch {
      drifts.push({
        path,
        kind: "missing",
        detail: "projection missing — run `agentsdir sync`.",
      });
      continue;
    }
    if (
      path.endsWith(".md") &&
      !current.toString("utf8").includes(GENERATED_HEADER)
    ) {
      drifts.push({
        path,
        kind: "header-removed",
        detail:
          "the generated header was removed — edit the source in .agents/ and run `agentsdir sync`.",
      });
      continue;
    }
    if (sha256(current) !== recorded) {
      drifts.push({
        path,
        kind: "modified",
        detail:
          "content differs from the fingerprint recorded in .agents.toml — move your edits into .agents/ and run `agentsdir sync`.",
      });
    }
  }
  return drifts;
}

interface ExpectedCopy {
  path: string;
  content: Buffer;
  isMarkdown: boolean;
}

async function expectedCopies(
  root: string,
  overlay: Record<string, Buffer>,
): Promise<ExpectedCopy[]> {
  const files: ExpectedCopy[] = [
    {
      path: "CLAUDE.md",
      content: Buffer.from(CLAUDE_MD_COPY, "utf8"),
      isMarkdown: true,
    },
  ];
  for (const spec of CLAUDE_PROJECTIONS) {
    if (spec.kind !== "dir") {
      continue;
    }
    const seenSources = new Set<string>();
    for (const source of await walkFiles(
      toAbsolute(root, spec.source),
      spec.target,
    )) {
      const sourceRel = spec.source + source.rel.slice(spec.target.length);
      seenSources.add(sourceRel);
      const raw = overlay[sourceRel] ?? (await readFile(source.abs));
      files.push(toExpectedCopy(source.rel, raw));
    }
    // overlay entries for source files absent from disk (e.g. a regenerated
    // artifact planned but not written yet), appended in sorted order
    const extras = Object.keys(overlay)
      .filter(
        (key) => key.startsWith(`${spec.source}/`) && !seenSources.has(key),
      )
      .sort();
    for (const key of extras) {
      const rel = spec.target + key.slice(spec.source.length);
      files.push(toExpectedCopy(rel, overlay[key] ?? Buffer.alloc(0)));
    }
  }
  return files;
}

function toExpectedCopy(rel: string, raw: Buffer): ExpectedCopy {
  if (rel.endsWith(".md")) {
    const decorated = `${MD_HEADER_LINE}\n\n${raw.toString("utf8")}`;
    return {
      path: rel,
      content: Buffer.from(decorated, "utf8"),
      isMarkdown: true,
    };
  }
  return { path: rel, content: raw, isMarkdown: false };
}

/** Recursive, sorted by name (code units) so every output is deterministic. */
async function walkFiles(
  absDir: string,
  relPrefix: string,
): Promise<{ rel: string; abs: string }[]> {
  let entries;
  try {
    entries = await readdir(absDir, { withFileTypes: true });
  } catch {
    return [];
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const files: { rel: string; abs: string }[] = [];
  for (const entry of entries) {
    const rel = `${relPrefix}/${entry.name}`;
    const abs = join(absDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkFiles(abs, rel)));
    } else if (entry.isFile()) {
      files.push({ rel, abs });
    }
  }
  return files;
}

async function classifyLinkTarget(
  absTarget: string,
  expected: string,
): Promise<"correct" | "other-link" | "absent" | "foreign"> {
  let stats;
  try {
    stats = await lstat(absTarget);
  } catch {
    return "absent";
  }
  if (!stats.isSymbolicLink()) {
    return "foreign";
  }
  return normalizeLink(await readlink(absTarget)) === expected
    ? "correct"
    : "other-link";
}

async function classifyCopyTarget(
  absTarget: string,
  file: ExpectedCopy,
  previousHashes: Record<string, string>,
): Promise<"absent" | "unchanged" | "stale-ours" | "foreign"> {
  let current: Buffer;
  try {
    current = await readFile(absTarget);
  } catch {
    return "absent";
  }
  if (current.equals(file.content)) {
    return "unchanged";
  }
  if (file.isMarkdown && current.toString("utf8").includes(GENERATED_HEADER)) {
    return "stale-ours";
  }
  if (previousHashes[file.path] === sha256(current)) {
    return "stale-ours";
  }
  return "foreign";
}

function relativeLinkTarget(spec: ProjectionSpec): string {
  const depth = spec.target.split("/").length - 1;
  return `${"../".repeat(depth)}${spec.source}`;
}

function foreignTargetError(path: string): CliError {
  return new CliError(
    `${path} already exists and was not generated by agentsdir. Move its content into the source of truth (.agents/ or AGENTS.md) and delete the file, then rerun — or wait for \`agentsdir migrate\`.`,
    EXIT_CODES.driftOrInvariant,
  );
}

function normalizeLink(target: string): string {
  return target.replaceAll("\\", "/");
}

function toAbsolute(root: string, posixPath: string): string {
  return join(root, ...posixPath.split("/"));
}

function sha256(content: Buffer): string {
  return `sha256:${createHash("sha256").update(content).digest("hex")}`;
}
