/** Single source for the CLI version; kept in sync with package.json at release time. */
export const CLI_VERSION = "1.0.0";

/**
 * The day this version was cut, set by hand at release time beside
 * `CLI_VERSION` — never computed at build time, because every generated byte of
 * this CLI has to be reproducible and a build date would change the bundle at
 * each build.
 *
 * `doctor` reads it to say how old the embedded conventions are, offline. The
 * alternative — asking the npm registry — would send the package name out of
 * the repository on an ordinary command, which this product does not do.
 */
export const CLI_RELEASED = "2026-09-13";
